import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Lupa Password
    Autogenerated by FlutLab FTF Generator
  */
class Announcement extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final arg = ModalRoute.of(context)!.settings.arguments as Map;
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: MediaQuery.of(context).size.width,
        height: 844.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 206.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 242.0,
                child: Container(
                  width: 345.0,
                  height: 242.0,
                  child: ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Image.asset(
                      arg['img'],
                      color: null,
                      fit: BoxFit.cover,
                      width: 345.0,
                      height: 242.0,
                      colorBlendMode: BlendMode.dstATop,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 20.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: MediaQuery.of(context).size.width * 0.9,
                height: 159.0,
                child: Container(
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: 159.0,
                  child: Stack(
                      fit: StackFit.expand,
                      alignment: Alignment.center,
                      clipBehavior: Clip.none,
                      children: [
                        Positioned(
                          left: 53.0,
                          top: 0.0,
                          right: null,
                          bottom: null,
                          width: 244.0,
                          height: 82.0,
                          child: Container(
                            width: 244.0,
                            height: 82.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(0.0),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                clipBehavior: Clip.none,
                                children: [
                                  Positioned(
                                    left: 1.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 250.0,
                                    height: 30.0,
                                    child: Text(
                                      arg['title'],
                                      overflow: TextOverflow.visible,
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        height: 1.2599999687888406,
                                        fontSize: 22.0,
                                        fontFamily: 'Outfit',
                                        fontWeight: FontWeight.w600,
                                        color: Color.fromARGB(255, 0, 0, 0),

                                        /* letterSpacing: 0.0, */
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 36.0,
                                    right: null,
                                    bottom: null,
                                    width: 246.0,
                                    height: 48.0,
                                    child: Text(
                                      arg['desc'],
                                      overflow: TextOverflow.visible,
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        height: 1.6402273178100586,
                                        fontSize: 14.0,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w400,
                                        color: Color.fromARGB(255, 42, 42, 42),

                                        /* letterSpacing: 0.0, */
                                      ),
                                    ),
                                  )
                                ]),
                          ),
                        ),
                        Positioned(
                          left: 0.0,
                          top: 114.0,
                          right: null,
                          bottom: null,
                          width: MediaQuery.of(context).size.width * 0.9,
                          height: 45.0,
                          child: ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: GestureDetector(
                                onTap: () {
                                  arg['actButton']();
                                },
                                child: Container(
                                  width:
                                      MediaQuery.of(context).size.width * 0.9,
                                  height: 45.0,
                                  child: Stack(
                                      fit: StackFit.expand,
                                      alignment: Alignment.center,
                                      clipBehavior: Clip.none,
                                      children: [
                                        Positioned(
                                          left: 0.0,
                                          top: 0.0,
                                          right: 0.0,
                                          bottom: 0.0,
                                          width: null,
                                          height: null,
                                          child: LayoutBuilder(builder:
                                              (BuildContext context,
                                                  BoxConstraints constraints) {
                                            final double width =
                                                constraints.maxWidth;

                                            final double height =
                                                constraints.maxHeight;

                                            return Stack(children: [
                                              TransformHelper.translate(
                                                  x: 0,
                                                  y: 0,
                                                  z: 0,
                                                  child: Container(
                                                    width: width,
                                                    height: height,
                                                    child: Container(
                                                      width:
                                                          MediaQuery.of(context)
                                                                  .size
                                                                  .width *
                                                              0.9,
                                                      height: 45.0,
                                                      decoration: BoxDecoration(
                                                        borderRadius:
                                                            BorderRadius
                                                                .circular(10.0),
                                                      ),
                                                      child: ClipRRect(
                                                        borderRadius:
                                                            BorderRadius
                                                                .circular(10.0),
                                                        child: Container(
                                                          color: Color.fromARGB(
                                                              255,
                                                              47,
                                                              115,
                                                              254),
                                                        ),
                                                      ),
                                                    ),
                                                  ))
                                            ]);
                                          }),
                                        ),
                                        Positioned(
                                          left: 0.0,
                                          top: 0.0,
                                          right: 0.0,
                                          bottom: 0.0,
                                          width: null,
                                          height: null,
                                          child: LayoutBuilder(builder:
                                              (BuildContext context,
                                                  BoxConstraints constraints) {
                                            final double width =
                                                constraints.maxWidth *
                                                    0.15428571428571428;

                                            final double height =
                                                constraints.maxHeight *
                                                    0.5333333333333333;

                                            return Stack(children: [
                                              TransformHelper.translate(
                                                  x: constraints.maxWidth *
                                                      0.43142857142857144,
                                                  y: constraints.maxHeight *
                                                      0.28888888888888886,
                                                  z: 0,
                                                  child: Container(
                                                    width: width,
                                                    height: height,
                                                    child: Text(
                                                      arg['titleButton'],
                                                      overflow:
                                                          TextOverflow.visible,
                                                      textAlign: TextAlign.left,
                                                      style: TextStyle(
                                                        height:
                                                            1.3502273559570312,
                                                        fontSize: 14.0,
                                                        fontFamily: 'Poppins',
                                                        fontWeight:
                                                            FontWeight.w600,
                                                        color: Color.fromARGB(
                                                            255, 255, 255, 255),

                                                        /* letterSpacing: 0.28, */
                                                      ),
                                                    ),
                                                  ))
                                            ]);
                                          }),
                                        )
                                      ]),
                                ),
                              )),
                        )
                      ]),
                ),
              ),
            ]),
      ),
    ));
  }
}
