import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutterapp/bloc/kelas_bloc.dart';
import 'package:flutterapp/bloc/order_bloc.dart';
import 'package:flutterapp/bloc/user_bloc.dart';
import 'package:flutterapp/component/KembaliTombol.dart';
import '../component/CurrencyFormat.dart';
import '../helpers/mask/mask.dart';
import '../helpers/svg/svg.dart';
import '../helpers/transform/transform.dart';

/* Frame invoice
    Autogenerated by FlutLab FTF Generator
  */
class DetailPembayaran extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    OrderBloc ob = context.read<OrderBloc>();
    KelasBloc kb = context.read<KelasBloc>();
    UserBloc ub = context.read<UserBloc>();
    return Material(
      child: SingleChildScrollView(
          child: ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                width: MediaQuery.of(context).size.width,
                height: 990.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    clipBehavior: Clip.none,
                    children: [
                      LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        return SingleChildScrollView(
                          scrollDirection: Axis.vertical,
                          child: Container(
                              height: 907.0,
                              child: Stack(children: [
                                Container(
                                    width: constraints.maxWidth,
                                    child: Container(
                                      width: MediaQuery.of(context).size.width,
                                      height: 844.0,
                                      child: Stack(
                                          fit: StackFit.expand,
                                          alignment: Alignment.center,
                                          clipBehavior: Clip.none,
                                          children: [
                                            ClipRRect(
                                              borderRadius: BorderRadius.zero,
                                              child: Container(
                                                color: Color.fromARGB(
                                                    255, 255, 255, 255),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 92.0,
                                              right: null,
                                              bottom: null,
                                              width: 131.0,
                                              height: 25.0,
                                              child: Text(
                                                '''Deskripsi Kelas''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.26000001695421,
                                                  fontSize: 18.0,
                                                  fontFamily: 'Outfit',
                                                  fontWeight: FontWeight.w600,
                                                  color: Color.fromARGB(
                                                      255, 0, 0, 0),

                                                  /* letterSpacing: 0.36, */
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 22.0,
                                              top: 152.0,
                                              right: null,
                                              bottom: null,
                                              width: 213.0,
                                              height: 23.0,
                                              child: Text(
                                                '''APP-ON-LE39-AQ5-GUMV''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.2599999564034599,
                                                  fontSize: 14.0,
                                                  fontFamily: 'Outfit',
                                                  fontWeight: FontWeight.w600,
                                                  color: Color.fromARGB(
                                                      255, 0, 0, 0),

                                                  /* letterSpacing: 1.61, */
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 486.0,
                                              right: null,
                                              bottom: null,
                                              width: 150.0,
                                              height: 39.0,
                                              child: Container(
                                                width: 120.0,
                                                height: 39.0,
                                                decoration: BoxDecoration(
                                                  borderRadius:
                                                      BorderRadius.circular(
                                                          0.0),
                                                ),
                                                child: Stack(
                                                    fit: StackFit.expand,
                                                    alignment: Alignment.center,
                                                    clipBehavior: Clip.none,
                                                    children: [
                                                      Positioned(
                                                        left: 1.0,
                                                        top: 21.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 120.0,
                                                        height: 20.0,
                                                        child: Text(
                                                          '''Rp  ''' +
                                                              (CurrencyFormat().changeCurrency(ob
                                                                              .state[
                                                                          'transfer'] +
                                                                      ob.state[
                                                                          'harga']))
                                                                  .toString(),
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2599999564034599,
                                                            fontSize: 14.0,
                                                            fontFamily:
                                                                'Outfit',
                                                            fontWeight:
                                                                FontWeight.w600,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    0,
                                                                    0,
                                                                    0),

                                                            /* letterSpacing: 1.61, */
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0.0,
                                                        top: 0.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 150.0,
                                                        height: 15.0,
                                                        child: Text(
                                                          '''Total Pembayaran''',
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2102272727272727,
                                                            fontSize: 11.0,
                                                            fontFamily: 'Inter',
                                                            fontWeight:
                                                                FontWeight.w400,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    87,
                                                                    86,
                                                                    86),

                                                            /* letterSpacing: -0.16499999999999998, */
                                                          ),
                                                        ),
                                                      )
                                                    ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 557.0,
                                              right: null,
                                              bottom: null,
                                              width: 181.0,
                                              height: 39.0,
                                              child: Container(
                                                width: 181.0,
                                                height: 39.0,
                                                decoration: BoxDecoration(
                                                  borderRadius:
                                                      BorderRadius.circular(
                                                          0.0),
                                                ),
                                                child: Stack(
                                                    fit: StackFit.expand,
                                                    alignment: Alignment.center,
                                                    clipBehavior: Clip.none,
                                                    children: [
                                                      Positioned(
                                                        left: 1.0,
                                                        top: 21.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 182.0,
                                                        height: 20.0,
                                                        child: Text(
                                                          '''Menunggu Pembayaran''',
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2599999564034599,
                                                            fontSize: 14.0,
                                                            fontFamily:
                                                                'Outfit',
                                                            fontWeight:
                                                                FontWeight.w600,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    0,
                                                                    0,
                                                                    0),

                                                            /* letterSpacing: 1.61, */
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0.0,
                                                        top: 0.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 150.0,
                                                        height: 15.0,
                                                        child: Text(
                                                          '''Status Pembayaran''',
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2102272727272727,
                                                            fontSize: 11.0,
                                                            fontFamily: 'Inter',
                                                            fontWeight:
                                                                FontWeight.w400,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    87,
                                                                    86,
                                                                    86),

                                                            /* letterSpacing: -0.16499999999999998, */
                                                          ),
                                                        ),
                                                      )
                                                    ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 541.0,
                                              right: null,
                                              bottom: null,
                                              width: 349.0,
                                              height: 1.0,
                                              child: Container(
                                                width: 349.0,
                                                height: 1.0,
                                                child: SvgWidget(painters: [
                                                  SvgPathPainter.stroke(
                                                    1.0,
                                                    strokeJoin:
                                                        StrokeJoin.miter,
                                                  )
                                                    ..addPath(
                                                        'M0 0L349 0L349 -1L0 -1L0 0Z')
                                                    ..color = Color.fromARGB(
                                                        255, 225, 225, 225),
                                                ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 612.0,
                                              right: null,
                                              bottom: null,
                                              width: 349.0,
                                              height: 1.0,
                                              child: Container(
                                                width: 349.0,
                                                height: 1.0,
                                                child: SvgWidget(painters: [
                                                  SvgPathPainter.stroke(
                                                    1.0,
                                                    strokeJoin:
                                                        StrokeJoin.miter,
                                                  )
                                                    ..addPath(
                                                        'M0 0L349 0L349 -1L0 -1L0 0Z')
                                                    ..color = Color.fromARGB(
                                                        255, 225, 225, 225),
                                                ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 628.0,
                                              right: null,
                                              bottom: null,
                                              width: 177.0,
                                              height: 39.0,
                                              child: Container(
                                                width: 177.0,
                                                height: 39.0,
                                                decoration: BoxDecoration(
                                                  borderRadius:
                                                      BorderRadius.circular(
                                                          0.0),
                                                ),
                                                child: Stack(
                                                    fit: StackFit.expand,
                                                    alignment: Alignment.center,
                                                    clipBehavior: Clip.none,
                                                    children: [
                                                      Positioned(
                                                        left: 1.0,
                                                        top: 21.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 178.0,
                                                        height: 20.0,
                                                        child: Text(
                                                          ob.state['bank'],
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2599999564034599,
                                                            fontSize: 14.0,
                                                            fontFamily:
                                                                'Outfit',
                                                            fontWeight:
                                                                FontWeight.w600,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    0,
                                                                    0,
                                                                    0),

                                                            /* letterSpacing: 1.61, */
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0.0,
                                                        top: 0.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 150.0,
                                                        height: 15.0,
                                                        child: Text(
                                                          '''Metode Pembayaran''',
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2102272727272727,
                                                            fontSize: 11.0,
                                                            fontFamily: 'Inter',
                                                            fontWeight:
                                                                FontWeight.w400,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    87,
                                                                    86,
                                                                    86),

                                                            /* letterSpacing: -0.16499999999999998, */
                                                          ),
                                                        ),
                                                      )
                                                    ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 683.0,
                                              right: null,
                                              bottom: null,
                                              width: 349.0,
                                              height: 1.0,
                                              child: Container(
                                                width: 349.0,
                                                height: 1.0,
                                                child: SvgWidget(painters: [
                                                  SvgPathPainter.stroke(
                                                    1.0,
                                                    strokeJoin:
                                                        StrokeJoin.miter,
                                                  )
                                                    ..addPath(
                                                        'M0 0L349 0L349 -1L0 -1L0 0Z')
                                                    ..color = Color.fromARGB(
                                                        255, 225, 225, 225),
                                                ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 131.0,
                                              right: null,
                                              bottom: null,
                                              width: 56.0,
                                              height: 15.0,
                                              child: Text(
                                                '''No Invoice''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.2102272727272727,
                                                  fontSize: 11.0,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  color: Color.fromARGB(
                                                      255, 87, 86, 86),

                                                  /* letterSpacing: -0.16499999999999998, */
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 22.0,
                                              top: 223.0,
                                              right: null,
                                              bottom: null,
                                              width: 300.0,
                                              height: 20.0,
                                              child: Text(
                                                kb.state['title'],
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.2599999564034599,
                                                  fontSize: 14.0,
                                                  fontFamily: 'Outfit',
                                                  fontWeight: FontWeight.w600,
                                                  color: Color.fromARGB(
                                                      255, 0, 0, 0),

                                                  /* letterSpacing: 1.61, */
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 202.0,
                                              right: null,
                                              bottom: null,
                                              width: 33.0,
                                              height: 18.0,
                                              child: Text(
                                                '''Kelas''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.2102272727272727,
                                                  fontSize: 11.0,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  color: Color.fromARGB(
                                                      255, 87, 86, 86),

                                                  /* letterSpacing: -0.16499999999999998, */
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 22.0,
                                              top: 294.0,
                                              right: null,
                                              bottom: null,
                                              width: 52.0,
                                              height: 23.0,
                                              child: Text(
                                                '''Umum''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.2599999564034599,
                                                  fontSize: 14.0,
                                                  fontFamily: 'Outfit',
                                                  fontWeight: FontWeight.w600,
                                                  color: Color.fromARGB(
                                                      255, 0, 0, 0),

                                                  /* letterSpacing: 1.61, */
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 273.0,
                                              right: null,
                                              bottom: null,
                                              width: 47.0,
                                              height: 18.0,
                                              child: Text(
                                                '''kategori''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.2102272727272727,
                                                  fontSize: 11.0,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  color: Color.fromARGB(
                                                      255, 87, 86, 86),

                                                  /* letterSpacing: -0.16499999999999998, */
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 22.0,
                                              top: 365.0,
                                              right: null,
                                              bottom: null,
                                              width: 159.0,
                                              height: 20.0,
                                              child: Text(
                                                ob.state['sesi'] +
                                                    ''' Sesi (pertemuan)''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.2599999564034599,
                                                  fontSize: 14.0,
                                                  fontFamily: 'Outfit',
                                                  fontWeight: FontWeight.w600,
                                                  color: Color.fromARGB(
                                                      255, 0, 0, 0),

                                                  /* letterSpacing: 1.61, */
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 344.0,
                                              right: null,
                                              bottom: null,
                                              width: 27.0,
                                              height: 18.0,
                                              child: Text(
                                                '''Sesi''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.2102272727272727,
                                                  fontSize: 11.0,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  color: Color.fromARGB(
                                                      255, 87, 86, 86),

                                                  /* letterSpacing: -0.16499999999999998, */
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 415.0,
                                              right: null,
                                              bottom: null,
                                              width: 98.0,
                                              height: 39.0,
                                              child: Container(
                                                width: 98.0,
                                                height: 39.0,
                                                decoration: BoxDecoration(
                                                  borderRadius:
                                                      BorderRadius.circular(
                                                          0.0),
                                                ),
                                                child: Stack(
                                                    fit: StackFit.expand,
                                                    alignment: Alignment.center,
                                                    clipBehavior: Clip.none,
                                                    children: [
                                                      Positioned(
                                                        left: 1.0,
                                                        top: 21.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 99.0,
                                                        height: 20.0,
                                                        child: Text(
                                                          '''25 Juni 2022''',
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2599999564034599,
                                                            fontSize: 14.0,
                                                            fontFamily:
                                                                'Outfit',
                                                            fontWeight:
                                                                FontWeight.w600,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    0,
                                                                    0,
                                                                    0),

                                                            /* letterSpacing: 1.61, */
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0.0,
                                                        top: 0.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 46.0,
                                                        height: 18.0,
                                                        child: Text(
                                                          '''Tanggal''',
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2102272727272727,
                                                            fontSize: 11.0,
                                                            fontFamily: 'Inter',
                                                            fontWeight:
                                                                FontWeight.w400,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    87,
                                                                    86,
                                                                    86),

                                                            /* letterSpacing: -0.16499999999999998, */
                                                          ),
                                                        ),
                                                      )
                                                    ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 186.0,
                                              right: null,
                                              bottom: null,
                                              width: 349.0,
                                              height: 1.0,
                                              child: Container(
                                                width: 349.0,
                                                height: 1.0,
                                                child: SvgWidget(painters: [
                                                  SvgPathPainter.stroke(
                                                    1.0,
                                                    strokeJoin:
                                                        StrokeJoin.miter,
                                                  )
                                                    ..addPath(
                                                        'M0 0L349 0L349 -1L0 -1L0 0Z')
                                                    ..color = Color.fromARGB(
                                                        255, 225, 225, 225),
                                                ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 257.0,
                                              right: null,
                                              bottom: null,
                                              width: 349.0,
                                              height: 1.0,
                                              child: Container(
                                                width: 349.0,
                                                height: 1.0,
                                                child: SvgWidget(painters: [
                                                  SvgPathPainter.stroke(
                                                    1.0,
                                                    strokeJoin:
                                                        StrokeJoin.miter,
                                                  )
                                                    ..addPath(
                                                        'M0 0L349 0L349 -1L0 -1L0 0Z')
                                                    ..color = Color.fromARGB(
                                                        255, 225, 225, 225),
                                                ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 328.0,
                                              right: null,
                                              bottom: null,
                                              width: 349.0,
                                              height: 1.0,
                                              child: Container(
                                                width: 349.0,
                                                height: 1.0,
                                                child: SvgWidget(painters: [
                                                  SvgPathPainter.stroke(
                                                    1.0,
                                                    strokeJoin:
                                                        StrokeJoin.miter,
                                                  )
                                                    ..addPath(
                                                        'M0 0L349 0L349 -1L0 -1L0 0Z')
                                                    ..color = Color.fromARGB(
                                                        255, 225, 225, 225),
                                                ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 738.0,
                                              right: null,
                                              bottom: null,
                                              width: 140.0,
                                              height: 39.0,
                                              child: Container(
                                                width: 140.0,
                                                height: 39.0,
                                                decoration: BoxDecoration(
                                                  borderRadius:
                                                      BorderRadius.circular(
                                                          0.0),
                                                ),
                                                child: Stack(
                                                    fit: StackFit.expand,
                                                    alignment: Alignment.center,
                                                    clipBehavior: Clip.none,
                                                    children: [
                                                      Positioned(
                                                        left: 1.0,
                                                        top: 21.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 141.0,
                                                        height: 20.0,
                                                        child: Text(
                                                          ub.state['username'],
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2599999564034599,
                                                            fontSize: 14.0,
                                                            fontFamily:
                                                                'Outfit',
                                                            fontWeight:
                                                                FontWeight.w600,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    0,
                                                                    0,
                                                                    0),

                                                            /* letterSpacing: 1.61, */
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0.0,
                                                        top: 0.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 35.0,
                                                        height: 18.0,
                                                        child: Text(
                                                          '''Nama''',
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2102272727272727,
                                                            fontSize: 11.0,
                                                            fontFamily: 'Inter',
                                                            fontWeight:
                                                                FontWeight.w400,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    87,
                                                                    86,
                                                                    86),

                                                            /* letterSpacing: -0.16499999999999998, */
                                                          ),
                                                        ),
                                                      )
                                                    ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 809.0,
                                              right: null,
                                              bottom: null,
                                              width: 228.0,
                                              height: 39.0,
                                              child: Container(
                                                width: 228.0,
                                                height: 39.0,
                                                decoration: BoxDecoration(
                                                  borderRadius:
                                                      BorderRadius.circular(
                                                          0.0),
                                                ),
                                                child: Stack(
                                                    fit: StackFit.expand,
                                                    alignment: Alignment.center,
                                                    clipBehavior: Clip.none,
                                                    children: [
                                                      Positioned(
                                                        left: 1.0,
                                                        top: 21.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 232.0,
                                                        height: 23.0,
                                                        child: Text(
                                                          ub.state['email'],
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2599999564034599,
                                                            fontSize: 14.0,
                                                            fontFamily:
                                                                'Outfit',
                                                            fontWeight:
                                                                FontWeight.w600,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    0,
                                                                    0,
                                                                    0),

                                                            /* letterSpacing: 1.61, */
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 0.0,
                                                        top: 0.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 32.0,
                                                        height: 18.0,
                                                        child: Text(
                                                          '''Email''',
                                                          overflow: TextOverflow
                                                              .visible,
                                                          textAlign:
                                                              TextAlign.left,
                                                          style: TextStyle(
                                                            height:
                                                                1.2102272727272727,
                                                            fontSize: 11.0,
                                                            fontFamily: 'Inter',
                                                            fontWeight:
                                                                FontWeight.w400,
                                                            color:
                                                                Color.fromARGB(
                                                                    255,
                                                                    87,
                                                                    86,
                                                                    86),

                                                            /* letterSpacing: -0.16499999999999998, */
                                                          ),
                                                        ),
                                                      )
                                                    ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 793.0,
                                              right: null,
                                              bottom: null,
                                              width: 349.0,
                                              height: 1.0,
                                              child: Container(
                                                width: 349.0,
                                                height: 1.0,
                                                child: SvgWidget(painters: [
                                                  SvgPathPainter.stroke(
                                                    1.0,
                                                    strokeJoin:
                                                        StrokeJoin.miter,
                                                  )
                                                    ..addPath(
                                                        'M0 0L349 0L349 -1L0 -1L0 0Z')
                                                    ..color = Color.fromARGB(
                                                        255, 225, 225, 225),
                                                ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 399.0,
                                              right: null,
                                              bottom: null,
                                              width: 349.0,
                                              height: 1.0,
                                              child: Container(
                                                width: 349.0,
                                                height: 1.0,
                                                child: SvgWidget(painters: [
                                                  SvgPathPainter.stroke(
                                                    1.0,
                                                    strokeJoin:
                                                        StrokeJoin.miter,
                                                  )
                                                    ..addPath(
                                                        'M0 0L349 0L349 -1L0 -1L0 0Z')
                                                    ..color = Color.fromARGB(
                                                        255, 225, 225, 225),
                                                ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 470.0,
                                              right: null,
                                              bottom: null,
                                              width: 349.0,
                                              height: 1.0,
                                              child: Container(
                                                width: 349.0,
                                                height: 1.0,
                                                child: SvgWidget(painters: [
                                                  SvgPathPainter.stroke(
                                                    1.0,
                                                    strokeJoin:
                                                        StrokeJoin.miter,
                                                  )
                                                    ..addPath(
                                                        'M0 0L349 0L349 -1L0 -1L0 0Z')
                                                    ..color = Color.fromARGB(
                                                        255, 225, 225, 225),
                                                ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 21.0,
                                              top: 699.0,
                                              right: null,
                                              bottom: null,
                                              width: 135.0,
                                              height: 25.0,
                                              child: Text(
                                                '''Data Pembeli''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.26000001695421,
                                                  fontSize: 18.0,
                                                  fontFamily: 'Outfit',
                                                  fontWeight: FontWeight.w600,
                                                  color: Color.fromARGB(
                                                      255, 0, 0, 0),

                                                  /* letterSpacing: 2.0700000000000003, */
                                                ),
                                              ),
                                            ),
                                            Positioned(
                                              left: 41.0,
                                              top: 858.0,
                                              right: null,
                                              bottom: null,
                                              width: 307.0,
                                              height: 49.0,
                                              child: Container(
                                                width: 307.0,
                                                height: 49.0,
                                                child: ClipRRect(
                                                  borderRadius:
                                                      BorderRadius.zero,
                                                  child: Container(
                                                    color: Color.fromARGB(
                                                        255, 255, 255, 255),
                                                  ),
                                                ),
                                              ),
                                            )
                                          ]),
                                    ))
                              ])),
                        );
                      }),
                      Positioned(
                        left: -35.0,
                        top: 0.0,
                        right: null,
                        bottom: null,
                        width: MediaQuery.of(context).size.width,
                        height: 83.0,
                        child: Container(
                          width: MediaQuery.of(context).size.width,
                          height: 83.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              clipBehavior: Clip.none,
                              children: [
                                Positioned(
                                  left: 39.0,
                                  top: 0.0,
                                  right: null,
                                  bottom: null,
                                  width: MediaQuery.of(context).size.width,
                                  height: 83.0,
                                  child: Container(
                                    width: MediaQuery.of(context).size.width,
                                    height: 83.0,
                                    child: ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color:
                                            Color.fromARGB(255, 255, 255, 255),
                                      ),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 0.0,
                                  right: null,
                                  bottom: null,
                                  width: MediaQuery.of(context).size.width,
                                  height: 76.00000762939453,
                                  child: Container(
                                    width: MediaQuery.of(context).size.width,
                                    height: 76.00000762939453,
                                    child: Stack(
                                        fit: StackFit.expand,
                                        alignment: Alignment.center,
                                        clipBehavior: Clip.none,
                                        children: [
                                          Positioned(
                                            left: 172.0,
                                            top: 54.0,
                                            right: null,
                                            bottom: null,
                                            width: 125.0,
                                            height: 21.0,
                                            child: Text(
                                              '''Detail Pembayaran''',
                                              overflow: TextOverflow.visible,
                                              textAlign: TextAlign.left,
                                              style: TextStyle(
                                                height: 1.3502273559570312,
                                                fontSize: 14.0,
                                                fontFamily: 'Outfit',
                                                fontWeight: FontWeight.w600,
                                                color: Color.fromARGB(
                                                    255, 42, 42, 42),

                                                /* letterSpacing: 0.0, */
                                              ),
                                            ),
                                          ),
                                        ]),
                                  ),
                                ),
                              ]),
                        ),
                      ),
                      KembaliTombol()
                    ]),
              ))),
    );
  }
}
