import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutterapp/bloc/user_bloc.dart';
import 'package:flutterapp/component/KembaliTombol.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import '../helpers/mask/mask.dart';
import '../helpers/svg/svg.dart';

/* Frame Profil
    Autogenerated by FlutLab FTF Generator
  */
class EditProfil extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    UserBloc ub = context.read<UserBloc>();
    return Material(
      child: SingleChildScrollView(
          child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: MediaQuery.of(context).size.width,
          height: 844.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              clipBehavior: Clip.none,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 168.0,
                  top: 53.0,
                  right: null,
                  bottom: null,
                  width: 100.0,
                  height: 24.0,
                  child: Text(
                    '''Edit Profil''',
                    overflow: TextOverflow.visible,
                    textAlign: TextAlign.left,
                    style: TextStyle(
                      height: 1.3502273559570312,
                      fontSize: 14.0,
                      fontFamily: 'Outfit',
                      fontWeight: FontWeight.w600,
                      color: Color.fromARGB(255, 42, 42, 42),

                      /* letterSpacing: 0.0, */
                    ),
                  ),
                ),
                Positioned(
                  left: 101.00006103515625,
                  top: 96.0,
                  right: null,
                  bottom: null,
                  width: 188.6761932373047,
                  height: 186.6761932373047,
                  child: Container(
                    width: 188.6761932373047,
                    height: 186.6761932373047,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0.0),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                              // left: 38.99995803833008,
                              top: 41.2001953125,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 180.0,
                              child: Center(
                                child: Image.asset(
                                  "assets/images/profil_photo.png",
                                  color: null,
                                  fit: BoxFit.fill,
                                  width: 200.0,
                                  height: 300.1999969482422,
                                  colorBlendMode: BlendMode.dstATop,
                                ),
                              )),
                        ]),
                  ),
                ),
                Positioned(
                  left: 42.0,
                  top: 315.0,
                  right: null,
                  bottom: null,
                  width: 34.0,
                  height: 19.0,
                  child: Text(
                    '''Email''',
                    overflow: TextOverflow.visible,
                    textAlign: TextAlign.left,
                    style: TextStyle(
                      height: 1.2599999687888406,
                      fontSize: 11.0,
                      fontFamily: 'Outfit',
                      fontWeight: FontWeight.w400,
                      color: Color.fromARGB(255, 120, 120, 120),

                      /* letterSpacing: 0.22, */
                    ),
                  ),
                ),
                Positioned(
                  left: 20.0,
                  top: 754.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: 45.0,
                  child: ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Container(
                      width: MediaQuery.of(context).size.width * 0.9,
                      height: 45.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          clipBehavior: Clip.none,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height = constraints.maxHeight;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Container(
                                          width: MediaQuery.of(context)
                                                  .size
                                                  .width *
                                              0.9,
                                          height: 45.0,
                                          decoration: BoxDecoration(
                                            borderRadius:
                                                BorderRadius.circular(10.0),
                                          ),
                                          child: ClipRRect(
                                            borderRadius:
                                                BorderRadius.circular(10.0),
                                            child: Container(
                                              color: Color.fromARGB(
                                                  255, 47, 115, 254),
                                            ),
                                          ),
                                        ),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16857142857142857;

                                final double height =
                                    constraints.maxHeight * 0.5333333333333333;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.43142857142857144,
                                      y: constraints.maxHeight *
                                          0.28888888888888886,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Text(
                                          '''Update''',
                                          overflow: TextOverflow.visible,
                                          textAlign: TextAlign.left,
                                          style: TextStyle(
                                            height: 1.3502273559570312,
                                            fontSize: 14.0,
                                            fontFamily: 'Poppins',
                                            fontWeight: FontWeight.w600,
                                            color: Color.fromARGB(
                                                255, 255, 255, 255),

                                            /* letterSpacing: 0.28, */
                                          ),
                                        ),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ),
                  ),
                ),
                Positioned(
                  left: 35.0,
                  top: 344.67578125,
                  right: null,
                  bottom: null,
                  width: 320.0,
                  height: 244.32423400878906,
                  child: ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Container(
                      width: 320.0,
                      height: 244.32423400878906,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          clipBehavior: Clip.none,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.0625;

                                final double height =
                                    constraints.maxHeight * 0.08185843733896876;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.9125,
                                      y: constraints.maxHeight *
                                          0.5907077508521248,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: ClipRRect(
                                          borderRadius: BorderRadius.zero,
                                          child: Container(
                                            width: 20.0,
                                            height: 20.0,
                                            child: Stack(
                                                fit: StackFit.expand,
                                                alignment: Alignment.center,
                                                clipBehavior: Clip.none,
                                                children: [
                                                  Positioned(
                                                    left: 0.0,
                                                    top: 0.0,
                                                    right: 0.0,
                                                    bottom: 0.0,
                                                    width: null,
                                                    height: null,
                                                    child: LayoutBuilder(
                                                        builder: (BuildContext
                                                                context,
                                                            BoxConstraints
                                                                constraints) {
                                                      final double width =
                                                          constraints.maxWidth *
                                                              0.8010542869567872;

                                                      final double height =
                                                          constraints
                                                                  .maxHeight *
                                                              0.5833333492279053;

                                                      return Stack(children: [
                                                        TransformHelper
                                                            .translate(
                                                                x: constraints
                                                                        .maxWidth *
                                                                    0.09946650266647339,
                                                                y: constraints
                                                                        .maxHeight *
                                                                    0.20833332538604737,
                                                                z: 0,
                                                                child:
                                                                    Container(
                                                                  width: width,
                                                                  height:
                                                                      height,
                                                                  child:
                                                                      Container(
                                                                    width:
                                                                        16.021085739135742,
                                                                    height:
                                                                        11.666666984558105,
                                                                    child: Stack(
                                                                        fit: StackFit
                                                                            .expand,
                                                                        alignment:
                                                                            Alignment
                                                                                .center,
                                                                        clipBehavior:
                                                                            Clip.none,
                                                                        children: [
                                                                          Positioned(
                                                                            left:
                                                                                0.0,
                                                                            top:
                                                                                0.0,
                                                                            right:
                                                                                0.0,
                                                                            bottom:
                                                                                0.0,
                                                                            width:
                                                                                null,
                                                                            height:
                                                                                null,
                                                                            child:
                                                                                LayoutBuilder(builder: (BuildContext context, BoxConstraints constraints) {
                                                                              double percentWidth = 1.0;
                                                                              double scaleX = (constraints.maxWidth * percentWidth) / 16.021085739135742;

                                                                              double percentHeight = 1.0;
                                                                              double scaleY = (constraints.maxHeight * percentHeight) / 11.666666984558105;

                                                                              return Stack(children: [
                                                                                TransformHelper.translateAndScale(
                                                                                    translateX: 0,
                                                                                    translateY: 0,
                                                                                    translateZ: 0,
                                                                                    scaleX: scaleX,
                                                                                    scaleY: scaleY,
                                                                                    scaleZ: 1,
                                                                                    child: Container(
                                                                                      width: 16.021085739135742,
                                                                                      height: 11.666666984558105,
                                                                                      child: SvgWidget(painters: [
                                                                                        SvgPathPainter.stroke(
                                                                                          2.0,
                                                                                          strokeCap: StrokeCap.round,
                                                                                          strokeJoin: StrokeJoin.miter,
                                                                                        )
                                                                                          ..addPath('M15.7248 6.69833L16.5187 7.30645L16.5188 7.30631L15.7248 6.69833ZM0.296503 6.69833L1.09037 6.0902L1.08622 6.08486L0.296503 6.69833ZM0 5.83333L-1 5.83333L0 5.83333ZM0.296503 4.96833L1.08624 5.58182L1.09035 5.57645L0.296503 4.96833ZM14.9304 5.57569C15.0515 5.73413 15.0509 5.93358 14.9309 6.09036L16.5188 7.30631C17.1887 6.43142 17.1881 5.23587 16.5193 4.36098L14.9304 5.57569ZM14.931 6.09022C14.336 6.86696 13.3381 8.03573 12.0945 9.00189C10.8397 9.9768 9.43662 10.6667 8.01067 10.6667L8.01067 12.6667C10.0697 12.6667 11.9016 11.6845 13.3216 10.5812C14.7528 9.46928 15.8695 8.15387 16.5187 7.30645L14.931 6.09022ZM8.01067 10.6667C6.58472 10.6667 5.18163 9.9768 3.9268 9.00189C2.68323 8.03573 1.68537 6.86696 1.09035 6.09022L-0.497346 7.30645C0.151807 8.15387 1.26852 9.46928 2.69975 10.5812C4.11971 11.6845 5.95162 12.6667 8.01067 12.6667L8.01067 10.6667ZM1.08622 6.08486C1.03034 6.01292 1 5.92443 1 5.83333L-1 5.83333C-1 6.36877 -0.821689 6.88897 -0.493211 7.31181L1.08622 6.08486ZM1 5.83333C1 5.74224 1.03034 5.65374 1.08622 5.58181L-0.493211 4.35486C-0.821689 4.7777 -1 5.29789 -1 5.83333L1 5.83333ZM1.09035 5.57645C1.68537 4.7997 2.68323 3.63094 3.9268 2.66478C5.18163 1.68987 6.58472 1 8.01067 1L8.01067 -1C5.95162 -1 4.11971 -0.0177833 2.69975 1.08543C1.26852 2.19739 0.151807 3.5128 -0.497346 4.36022L1.09035 5.57645ZM8.01067 1C9.43662 1 10.8397 1.68987 12.0945 2.66478C13.3381 3.63094 14.336 4.7997 14.931 5.57645L16.5187 4.36022C15.8695 3.5128 14.7528 2.19739 13.3216 1.08543C11.9016 -0.0177833 10.0697 -1 8.01067 -1L8.01067 1Z')
                                                                                          ..color = Color.fromARGB(127, 120, 120, 120),
                                                                                      ]),
                                                                                    ))
                                                                              ]);
                                                                            }),
                                                                          ),
                                                                          Positioned(
                                                                            left:
                                                                                0.0,
                                                                            top:
                                                                                0.0,
                                                                            right:
                                                                                0.0,
                                                                            bottom:
                                                                                0.0,
                                                                            width:
                                                                                null,
                                                                            height:
                                                                                null,
                                                                            child:
                                                                                LayoutBuilder(builder: (BuildContext context, BoxConstraints constraints) {
                                                                              double percentWidth = 0.3120887111780556;
                                                                              double scaleX = (constraints.maxWidth * percentWidth) / 5.0;

                                                                              double percentHeight = 0.4285714168937842;
                                                                              double scaleY = (constraints.maxHeight * percentHeight) / 5.0;

                                                                              return Stack(children: [
                                                                                TransformHelper.translateAndScale(
                                                                                    translateX: constraints.maxWidth * 0.34396356139526074,
                                                                                    translateY: constraints.maxHeight * 0.2857142915531079,
                                                                                    translateZ: 0,
                                                                                    scaleX: scaleX,
                                                                                    scaleY: scaleY,
                                                                                    scaleZ: 1,
                                                                                    child: Container(
                                                                                        width: 5.0,
                                                                                        height: 5.0,
                                                                                        child: SvgWidget(painters: [
                                                                                          SvgPathPainter.stroke(
                                                                                            2.0,
                                                                                            strokeCap: StrokeCap.round,
                                                                                            strokeJoin: StrokeJoin.miter,
                                                                                          )
                                                                                            ..addPath('M4 2.5C4 3.32843 3.32843 4 2.5 4L2.5 6C4.433 6 6 4.433 6 2.5L4 2.5ZM2.5 4C1.67157 4 1 3.32843 1 2.5L-1 2.5C-1 4.433 0.567003 6 2.5 6L2.5 4ZM1 2.5C1 1.67157 1.67157 1 2.5 1L2.5 -1C0.567003 -1 -1 0.567003 -1 2.5L1 2.5ZM2.5 1C3.32843 1 4 1.67157 4 2.5L6 2.5C6 0.567003 4.433 -1 2.5 -1L2.5 1Z')
                                                                                            ..color = Color.fromARGB(127, 120, 120, 120),
                                                                                        ])))
                                                                              ]);
                                                                            }),
                                                                          )
                                                                        ]),
                                                                  ),
                                                                ))
                                                      ]);
                                                    }),
                                                  )
                                                ]),
                                          ),
                                        ),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height =
                                    constraints.maxHeight * 0.12820757988695128;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                          width: width,
                                          height: height,
                                          child: TextFormField(
                                            initialValue: ub.state['email'],
                                          )))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.178125;

                                final double height =
                                    constraints.maxHeight * 0.07776551547202032;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.021875,
                                      y: constraints.maxHeight *
                                          0.19236732774657658,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Text(
                                          '''Username''',
                                          overflow: TextOverflow.visible,
                                          textAlign: TextAlign.left,
                                          style: TextStyle(
                                            height: 1.2599999687888406,
                                            fontSize: 11.0,
                                            fontFamily: 'Outfit',
                                            fontWeight: FontWeight.w400,
                                            color: Color.fromARGB(
                                                255, 120, 120, 120),

                                            /* letterSpacing: 0.22, */
                                          ),
                                        ),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.16875;

                                final double height =
                                    constraints.maxHeight * 0.07776551547202032;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.021875,
                                      y: constraints.maxHeight *
                                          0.4870577021668641,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Text(
                                          '''Password''',
                                          overflow: TextOverflow.visible,
                                          textAlign: TextAlign.left,
                                          style: TextStyle(
                                            height: 1.2599999687888406,
                                            fontSize: 11.0,
                                            fontFamily: 'Outfit',
                                            fontWeight: FontWeight.w400,
                                            color: Color.fromARGB(
                                                255, 120, 120, 120),

                                            /* letterSpacing: 0.22, */
                                          ),
                                        ),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 1.0;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        320.0;

                                double percentHeight = 0.0061393828004226575;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        1.5;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: 0,
                                      translateY: constraints.maxHeight *
                                          0.4228979543072388,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: TransformHelper.rotate(
                                          a: 1.00,
                                          b: 0.00,
                                          c: -0.00,
                                          d: 1.00,
                                          child: Container(
                                              width: 320.0,
                                              height: 1.5,
                                              child: TextFormField(
                                                initialValue:
                                                    ub.state['username'],
                                              ))))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 1.0;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        320.0;

                                double percentHeight = 0.0061393828004226575;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        1.5;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: 0,
                                      translateY: constraints.maxHeight *
                                          0.6848449537919389,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: TransformHelper.rotate(
                                          a: 1.00,
                                          b: 0.00,
                                          c: -0.00,
                                          d: 1.00,
                                          child: Container(
                                              width: 320.0,
                                              height: 1.5,
                                              child: TextFormField(
                                                initialValue: '123456',
                                                obscureText: true,
                                              ))))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.225;

                                final double height =
                                    constraints.maxHeight * 0.065486749871175;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.021875,
                                      y: constraints.maxHeight *
                                          0.7503317036631139,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Text(
                                          '''Tanggal Lahir''',
                                          overflow: TextOverflow.visible,
                                          textAlign: TextAlign.left,
                                          style: TextStyle(
                                            height: 1.2599999687888406,
                                            fontSize: 11.0,
                                            fontFamily: 'Outfit',
                                            fontWeight: FontWeight.w400,
                                            color: Color.fromARGB(
                                                255, 120, 120, 120),

                                            /* letterSpacing: 0.22, */
                                          ),
                                        ),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.06875;

                                final double height =
                                    constraints.maxHeight * 0.11460181227455626;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.0875,
                                      y: constraints.maxHeight *
                                          0.873119359671567,
                                      z: 0,
                                      child: Container(
                                          width: width,
                                          height: height,
                                          child: TextFormField(
                                            initialValue: '21',
                                          )))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.234375;

                                final double height =
                                    constraints.maxHeight * 0.11460181227455626;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.3875,
                                      y: constraints.maxHeight *
                                          0.873119359671567,
                                      z: 0,
                                      child: Container(
                                          width: width,
                                          height: height,
                                          child: TextFormField(
                                            initialValue: 'Oktober',
                                          )))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.1375;

                                final double height =
                                    constraints.maxHeight * 0.11460181227455626;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.821875,
                                      y: constraints.maxHeight *
                                          0.873119359671567,
                                      z: 0,
                                      child: Container(
                                          width: width,
                                          height: height,
                                          child: TextFormField(
                                            initialValue: '2021',
                                          )))
                                ]);
                              }),
                            ),
                          ]),
                    ),
                  ),
                ),
                KembaliTombol(),
              ]),
        ),
      )),
    );
  }
}
