import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import '../component/Alert.dart';
import '../component/InputField.dart';
import '../helpers/mask/mask.dart';
import '../helpers/svg/svg.dart';

/* Frame Lupa Password
    Autogenerated by FlutLab FTF Generator
  */
class ForgotPass extends StatelessWidget {
  TextEditingController _emailController = TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Material(
      child: SingleChildScrollView(
          child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: MediaQuery.of(context).size.width,
          height: 990.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              clipBehavior: Clip.none,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -92.0,
                  top: -98.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width,
                  height: 706.0,
                  child: Container(
                    width: MediaQuery.of(context).size.width,
                    height: 706.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: MediaQuery.of(context).size.width,
                            height: 706.0,
                            child: Container(
                              width: MediaQuery.of(context).size.width,
                              height: 706.0,
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  clipBehavior: Clip.none,
                                  children: [
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: MediaQuery.of(context).size.width,
                                      height: 706.0,
                                      child: Mask.fromSVGPath(
                                        'M574 353C574 547.957 445.506 706 287 706C128.494 706 0 547.957 0 353C0 158.043 128.494 0 287 0C445.506 0 574 158.043 574 353Z',
                                        child: Stack(
                                            fit: StackFit.expand,
                                            alignment: Alignment.center,
                                            clipBehavior: Clip.none,
                                            children: [
                                              Positioned(
                                                left: -116.2430419921875,
                                                top: -315.53082275390625,
                                                right: null,
                                                bottom: null,
                                                width: 690.2430419921875,
                                                height: 1046.1815185546875,
                                                child: Container(
                                                  width: 690.2430419921875,
                                                  height: 1046.1815185546875,
                                                  child: ClipRRect(
                                                    borderRadius:
                                                        BorderRadius.zero,
                                                    child: Image.asset(
                                                      "assets/images/c963427706d1f6cefaa3c93b4c412c48f6678638.png",
                                                      color: null,
                                                      fit: BoxFit.cover,
                                                      width: 690.2430419921875,
                                                      height:
                                                          1046.1815185546875,
                                                      colorBlendMode:
                                                          BlendMode.dstATop,
                                                    ),
                                                  ),
                                                ),
                                              )
                                            ]),
                                        offset: Offset(0.0, 0.0),
                                      ),
                                    )
                                  ]),
                            ),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: MediaQuery.of(context).size.width,
                            height: 706.0,
                            child: Container(
                              width: MediaQuery.of(context).size.width,
                              height: 706.0,
                              child: SvgWidget(painters: [
                                SvgPathPainter.fill()
                                  ..addPath(
                                      'M574 353C574 547.957 445.506 706 287 706C128.494 706 0 547.957 0 353C0 158.043 128.494 0 287 0C445.506 0 574 158.043 574 353Z')
                                  ..color = Color.fromARGB(76, 29, 29, 29)
                                  ..setBlur(2.0),
                              ]),
                            ),
                          )
                        ]),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 487.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width,
                  height: 357.0,
                  child: Container(
                    width: MediaQuery.of(context).size.width,
                    height: 357.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(20.0),
                        topRight: Radius.circular(20.0),
                        bottomRight: Radius.circular(0.0),
                        bottomLeft: Radius.circular(0.0),
                      ),
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(20.0),
                        topRight: Radius.circular(20.0),
                        bottomRight: Radius.circular(0.0),
                        bottomLeft: Radius.circular(0.0),
                      ),
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 23.0,
                  top: 531.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width,
                  height: 102.0,
                  child: Container(
                    width: MediaQuery.of(context).size.width,
                    height: 102.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(0.0),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 210.0,
                            height: 36.0,
                            child: Text(
                              '''Lupa Kata Sandi''',
                              overflow: TextOverflow.visible,
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                height: 1.26000001695421,
                                fontSize: 27.0,
                                fontFamily: 'Outfit',
                                fontWeight: FontWeight.w600,
                                color: Color.fromARGB(255, 42, 42, 42),

                                /* letterSpacing: 0.54, */
                              ),
                            ),
                          ),
                          Positioned(
                            left: 0.0,
                            top: 42.0,
                            right: null,
                            bottom: null,
                            width: 334.0,
                            height: 62.0,
                            child: Text(
                              '''masukkan email yang terkait dengan akun Anda 
dan kami akan mengirim email berisi instruksi 
untuk mengatur ulang kata sandi Anda''',
                              overflow: TextOverflow.visible,
                              textAlign: TextAlign.left,
                              style: TextStyle(
                                height: 1.4252273014613561,
                                fontSize: 14.0,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                                color: Color.fromARGB(255, 120, 120, 120),

                                /* letterSpacing: 0.28, */
                              ),
                            ),
                          )
                        ]),
                  ),
                ),
                Positioned(
                    left: 20.0,
                    top: 665.0,
                    right: null,
                    bottom: null,
                    width: MediaQuery.of(context).size.width * 0.9,
                    height: 45.0,
                    child: InputField(
                      cont: _emailController,
                      hint: 'Masukkan Email..',
                      obs: false,
                    )),
                Positioned(
                  left: 20.0,
                  top: 742.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: 45.0,
                  child: GestureDetector(
                    onTap: () {
                      if (_emailController.text == '') {
                        print('kosong');
                        showDialog<void>(
                          context: context,
                          builder: (context) => Alert(
                            img: 'assets/images/email_pass_kosong.png',
                            added: '',
                            desc:
                                'Isi semua form dengan data  diri anda pastikan data yang dimasukan sudah benar',
                            title: 'Form Masih Kosong',
                            titleButton: 'Kembali',
                            addedFunc: () {},
                            buttonFunc: () {
                              Navigator.pop(context);
                            },
                          ),
                        );
                      } else {
                        print('gakosong');
                        showDialog<void>(
                          context: context,
                          builder: (context) => Alert(
                            img: 'assets/images/email_send.png',
                            added: 'Saya tidak menerima Email',
                            desc:
                                'kami telah mengirimkan instruksi pemulihan kata sandi ke email Anda',
                            title: 'Cek Email Anda',
                            titleButton: 'Buka Email',
                            addedFunc: () {
                              Navigator.pop(context);
                            },
                            buttonFunc: () {
                              Navigator.pushNamed(context, '/ChangePass');
                            },
                          ),
                        );
                      }
                    },
                    child: Container(
                      width: MediaQuery.of(context).size.width * 0.9,
                      height: 45.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          clipBehavior: Clip.none,
                          children: [
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width = constraints.maxWidth;

                                final double height = constraints.maxHeight;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: 0,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: Container(
                                          width: MediaQuery.of(context)
                                                  .size
                                                  .width *
                                              0.9,
                                          height: 45.0,
                                          child: Stack(
                                              fit: StackFit.expand,
                                              alignment: Alignment.center,
                                              clipBehavior: Clip.none,
                                              children: [
                                                Positioned(
                                                  left: 0.0,
                                                  top: 0.0,
                                                  right: 0.0,
                                                  bottom: 0.0,
                                                  width: null,
                                                  height: null,
                                                  child: LayoutBuilder(builder:
                                                      (BuildContext context,
                                                          BoxConstraints
                                                              constraints) {
                                                    final double width =
                                                        constraints.maxWidth;

                                                    final double height =
                                                        constraints.maxHeight;

                                                    return Stack(children: [
                                                      TransformHelper.translate(
                                                          x: 0,
                                                          y: 0,
                                                          z: 0,
                                                          child: Container(
                                                            width: width,
                                                            height: height,
                                                            child: Container(
                                                              width: MediaQuery.of(
                                                                          context)
                                                                      .size
                                                                      .width *
                                                                  0.9,
                                                              height: 45.0,
                                                              decoration:
                                                                  BoxDecoration(
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            10.0),
                                                              ),
                                                              child: ClipRRect(
                                                                borderRadius:
                                                                    BorderRadius
                                                                        .circular(
                                                                            10.0),
                                                                child:
                                                                    Container(
                                                                  color: Color
                                                                      .fromARGB(
                                                                          255,
                                                                          47,
                                                                          115,
                                                                          254),
                                                                ),
                                                              ),
                                                            ),
                                                          ))
                                                    ]);
                                                  }),
                                                ),
                                                Positioned(
                                                  left: 0.0,
                                                  top: 0.0,
                                                  right: 0.0,
                                                  bottom: 0.0,
                                                  width: null,
                                                  height: null,
                                                  child: LayoutBuilder(builder:
                                                      (BuildContext context,
                                                          BoxConstraints
                                                              constraints) {
                                                    final double width =
                                                        constraints.maxWidth *
                                                            0.12571428571428572;

                                                    final double height =
                                                        constraints.maxHeight *
                                                            0.5333333333333333;

                                                    return Stack(children: [
                                                      TransformHelper.translate(
                                                          x: constraints
                                                                  .maxWidth *
                                                              0.4342857142857143,
                                                          y: constraints
                                                                  .maxHeight *
                                                              0.28888888888888886,
                                                          z: 0,
                                                          child: Container(
                                                            width: width,
                                                            height: height,
                                                            child: Text(
                                                              '''Kirim''',
                                                              overflow:
                                                                  TextOverflow
                                                                      .visible,
                                                              textAlign:
                                                                  TextAlign
                                                                      .left,
                                                              style: TextStyle(
                                                                height:
                                                                    1.3502273559570312,
                                                                fontSize: 14.0,
                                                                fontFamily:
                                                                    'Poppins',
                                                                fontWeight:
                                                                    FontWeight
                                                                        .w600,
                                                                color: Color
                                                                    .fromARGB(
                                                                        255,
                                                                        255,
                                                                        255,
                                                                        255),

                                                                /* letterSpacing: 0.28, */
                                                              ),
                                                            ),
                                                          ))
                                                    ]);
                                                  }),
                                                )
                                              ]),
                                        ),
                                      )),
                                ]);
                              }),
                            )
                          ]),
                    ),
                  ),
                ),
              ]),
        ),
      )),
    );
  }
}
