import 'package:flutter/material.dart';
import 'package:flutterapp/component/KembaliTombol.dart';
import '../helpers/mask/mask.dart';
import '../helpers/svg/svg.dart';
import '../helpers/transform/transform.dart';

/* Frame Mindfull
    Autogenerated by FlutLab FTF Generator
  */
class KelasNotFound extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: SingleChildScrollView(
          child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: MediaQuery.of(context).size.width,
          height: 844.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              clipBehavior: Clip.none,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 19.0,
                  top: 50.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: 86.80000305175781,
                  child: Container(
                    width: MediaQuery.of(context).size.width * 0.9,
                    height: 86.80000305175781,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 41.79999923706055,
                            right: null,
                            bottom: null,
                            width: MediaQuery.of(context).size.width * 0.9,
                            height: 45.0,
                            child: Container(
                              width: MediaQuery.of(context).size.width * 0.9,
                              height: 45.0,
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  clipBehavior: Clip.none,
                                  children: [
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: 0.0,
                                      bottom: 0.0,
                                      width: null,
                                      height: null,
                                      child: LayoutBuilder(builder:
                                          (BuildContext context,
                                              BoxConstraints constraints) {
                                        final double width =
                                            constraints.maxWidth *
                                                0.8257142857142857;

                                        final double height =
                                            constraints.maxHeight;

                                        return Stack(children: [
                                          TransformHelper.translate(
                                              x: 0,
                                              y: 0,
                                              z: 0,
                                              child: Container(
                                                width: width,
                                                height: height,
                                                child: Container(
                                                  width: 289.0,
                                                  height: 45.0,
                                                  decoration: BoxDecoration(
                                                    borderRadius:
                                                        BorderRadius.circular(
                                                            10.0),
                                                  ),
                                                  child: Stack(
                                                      fit: StackFit.expand,
                                                      alignment:
                                                          Alignment.center,
                                                      clipBehavior: Clip.none,
                                                      children: [
                                                        Positioned(
                                                          left: 0.0,
                                                          top: 0.0,
                                                          right: 0.0,
                                                          bottom: 0.0,
                                                          width: null,
                                                          height: null,
                                                          child: LayoutBuilder(
                                                              builder: (BuildContext
                                                                      context,
                                                                  BoxConstraints
                                                                      constraints) {
                                                            final double width =
                                                                constraints
                                                                    .maxWidth;

                                                            final double
                                                                height =
                                                                constraints
                                                                    .maxHeight;

                                                            return Stack(
                                                                children: [
                                                                  TransformHelper
                                                                      .translate(
                                                                          x: 0,
                                                                          y: 0,
                                                                          z: 0,
                                                                          child:
                                                                              Container(
                                                                            width:
                                                                                width,
                                                                            height:
                                                                                height,
                                                                            child:
                                                                                Container(
                                                                              width: 289.0,
                                                                              height: 45.0,
                                                                              decoration: BoxDecoration(
                                                                                borderRadius: BorderRadius.circular(10.0),
                                                                              ),
                                                                              child: ClipRRect(
                                                                                borderRadius: BorderRadius.circular(10.0),
                                                                                child: Container(
                                                                                  color: Color.fromARGB(51, 195, 194, 200),
                                                                                ),
                                                                              ),
                                                                            ),
                                                                          ))
                                                                ]);
                                                          }),
                                                        ),
                                                        Positioned(
                                                          left: 0.0,
                                                          top: 0.0,
                                                          right: 0.0,
                                                          bottom: 0.0,
                                                          width: null,
                                                          height: null,
                                                          child: LayoutBuilder(
                                                              builder: (BuildContext
                                                                      context,
                                                                  BoxConstraints
                                                                      constraints) {
                                                            final double width =
                                                                constraints
                                                                        .maxWidth *
                                                                    0.36678200692041524;

                                                            final double
                                                                height =
                                                                constraints
                                                                        .maxHeight *
                                                                    0.4444444444444444;

                                                            return Stack(
                                                                children: [
                                                                  TransformHelper
                                                                      .translate(
                                                                          x: constraints.maxWidth *
                                                                              0.08996539792387544,
                                                                          y: constraints.maxHeight *
                                                                              0.3111111111111111,
                                                                          z: 0,
                                                                          child:
                                                                              Container(
                                                                            width:
                                                                                width,
                                                                            height:
                                                                                height,
                                                                            child:
                                                                                Text(
                                                                              '''Solve for Happy''',
                                                                              overflow: TextOverflow.visible,
                                                                              textAlign: TextAlign.left,
                                                                              style: TextStyle(
                                                                                height: 1.2599999564034599,
                                                                                fontSize: 14.0,
                                                                                fontFamily: 'Outfit',
                                                                                fontWeight: FontWeight.w400,
                                                                                color: Color.fromARGB(255, 42, 42, 42),

                                                                                /* letterSpacing: 0.28, */
                                                                              ),
                                                                            ),
                                                                          ))
                                                                ]);
                                                          }),
                                                        )
                                                      ]),
                                                ),
                                              ))
                                        ]);
                                      }),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: 0.0,
                                      bottom: 0.0,
                                      width: null,
                                      height: null,
                                      child: LayoutBuilder(builder:
                                          (BuildContext context,
                                              BoxConstraints constraints) {
                                        final double width =
                                            constraints.maxWidth *
                                                0.12857142857142856;

                                        final double height =
                                            constraints.maxHeight;

                                        return Stack(children: [
                                          TransformHelper.translate(
                                              x: constraints.maxWidth *
                                                  0.8714285714285714,
                                              y: 0,
                                              z: 0,
                                              child: Container(
                                                width: width,
                                                height: height,
                                                child: Container(
                                                  width: 45.0,
                                                  height: 45.0,
                                                  decoration: BoxDecoration(
                                                    borderRadius:
                                                        BorderRadius.circular(
                                                            0.0),
                                                  ),
                                                  child: Stack(
                                                      fit: StackFit.expand,
                                                      alignment:
                                                          Alignment.center,
                                                      clipBehavior: Clip.none,
                                                      children: [
                                                        Positioned(
                                                          left: 0.0,
                                                          top: 0.0,
                                                          right: 0.0,
                                                          bottom: 0.0,
                                                          width: null,
                                                          height: null,
                                                          child: LayoutBuilder(
                                                              builder: (BuildContext
                                                                      context,
                                                                  BoxConstraints
                                                                      constraints) {
                                                            final double width =
                                                                constraints
                                                                    .maxWidth;

                                                            final double
                                                                height =
                                                                constraints
                                                                    .maxHeight;

                                                            return Stack(
                                                                children: [
                                                                  TransformHelper
                                                                      .translate(
                                                                          x: 0,
                                                                          y: 0,
                                                                          z: 0,
                                                                          child:
                                                                              Container(
                                                                            width:
                                                                                width,
                                                                            height:
                                                                                height,
                                                                            child:
                                                                                Container(
                                                                              width: 45.0,
                                                                              height: 45.0,
                                                                              decoration: BoxDecoration(
                                                                                borderRadius: BorderRadius.circular(10.0),
                                                                              ),
                                                                              child: ClipRRect(
                                                                                borderRadius: BorderRadius.circular(10.0),
                                                                                child: Container(
                                                                                  color: Color.fromARGB(255, 47, 115, 254),
                                                                                ),
                                                                              ),
                                                                            ),
                                                                          ))
                                                                ]);
                                                          }),
                                                        ),
                                                        Positioned(
                                                          left: 0.0,
                                                          top: 0.0,
                                                          right: 0.0,
                                                          bottom: 0.0,
                                                          width: null,
                                                          height: null,
                                                          child: LayoutBuilder(
                                                              builder: (BuildContext
                                                                      context,
                                                                  BoxConstraints
                                                                      constraints) {
                                                            final double width =
                                                                constraints
                                                                        .maxWidth *
                                                                    0.4;

                                                            final double
                                                                height =
                                                                constraints
                                                                        .maxHeight *
                                                                    0.4;

                                                            return Stack(
                                                                children: [
                                                                  TransformHelper
                                                                      .translate(
                                                                          x: constraints.maxWidth *
                                                                              0.28888888888888886,
                                                                          y: constraints.maxHeight *
                                                                              0.3111111111111111,
                                                                          z: 0,
                                                                          child:
                                                                              Container(
                                                                            width:
                                                                                width,
                                                                            height:
                                                                                height,
                                                                            child:
                                                                                ClipRRect(
                                                                              borderRadius: BorderRadius.zero,
                                                                              child: Container(
                                                                                width: 18.0,
                                                                                height: 18.0,
                                                                                child: Stack(fit: StackFit.expand, alignment: Alignment.center, clipBehavior: Clip.none, children: [
                                                                                  Positioned(
                                                                                    left: 0.0,
                                                                                    top: 0.0,
                                                                                    right: 0.0,
                                                                                    bottom: 0.0,
                                                                                    width: null,
                                                                                    height: null,
                                                                                    child: LayoutBuilder(builder: (BuildContext context, BoxConstraints constraints) {
                                                                                      double percentWidth = 0.8347142007615831;
                                                                                      double scaleX = (constraints.maxWidth * percentWidth) / 15.024855613708496;

                                                                                      double percentHeight = 0.8348924848768446;
                                                                                      double scaleY = (constraints.maxHeight * percentHeight) / 15.028064727783203;

                                                                                      return Stack(children: [
                                                                                        TransformHelper.translateAndScale(
                                                                                            translateX: constraints.maxWidth * 0.08351147174835205,
                                                                                            translateY: constraints.maxHeight * 0.08333331346511841,
                                                                                            translateZ: 0,
                                                                                            scaleX: scaleX,
                                                                                            scaleY: scaleY,
                                                                                            scaleZ: 1,
                                                                                            child: Container(
                                                                                              width: 15.024855613708496,
                                                                                              height: 15.028064727783203,
                                                                                              child: SvgWidget(painters: [
                                                                                                SvgPathPainter.fill()
                                                                                                  ..addPath('M5.99679 3.95031e-07C5.05822 0.000502058 4.13285 0.221187 3.29507 0.644317C2.45728 1.06745 1.73045 1.68122 1.17298 2.43631C0.615518 3.19139 0.242971 4.06673 0.0852848 4.99196C-0.0724014 5.9172 -0.0108285 6.86652 0.265055 7.76363C0.540938 8.66075 1.02344 9.48062 1.67377 10.1574C2.32411 10.8341 3.12413 11.3489 4.00956 11.6602C4.89498 11.9716 5.8411 12.0709 6.77188 11.9501C7.70265 11.8294 8.59212 11.492 9.36879 10.965L13.0768 14.67C13.1798 14.7805 13.304 14.8692 13.442 14.9307C13.58 14.9922 13.729 15.0252 13.88 15.0279C14.0311 15.0306 14.1811 15.0028 14.3212 14.9462C14.4613 14.8896 14.5885 14.8054 14.6953 14.6986C14.8022 14.5917 14.8864 14.4645 14.943 14.3244C14.9996 14.1843 15.0273 14.0343 15.0247 13.8832C15.022 13.7322 14.989 13.5832 14.9275 13.4452C14.866 13.3072 14.7773 13.183 14.6668 13.08L10.9618 9.372C11.5747 8.46987 11.9302 7.41773 11.99 6.32871C12.0497 5.23968 11.8115 4.15496 11.3009 3.19119C10.7903 2.22742 10.0267 1.42105 9.09216 0.858775C8.1576 0.296504 7.08746 -0.000395312 5.99679 3.95031e-07L5.99679 3.95031e-07ZM2.24679 6C2.24679 5.00544 2.64188 4.05161 3.34514 3.34835C4.0484 2.64509 5.00223 2.25 5.99679 2.25C6.99135 2.25 7.94518 2.64509 8.64844 3.34835C9.3517 4.05161 9.74679 5.00544 9.74679 6C9.74679 6.99456 9.3517 7.94839 8.64844 8.65165C7.94518 9.35491 6.99135 9.75 5.99679 9.75C5.00223 9.75 4.0484 9.35491 3.34514 8.65165C2.64188 7.94839 2.24679 6.99456 2.24679 6Z')
                                                                                                  ..color = Color.fromARGB(255, 255, 255, 255),
                                                                                              ]),
                                                                                            ))
                                                                                      ]);
                                                                                    }),
                                                                                  )
                                                                                ]),
                                                                              ),
                                                                            ),
                                                                          ))
                                                                ]);
                                                          }),
                                                        )
                                                      ]),
                                                ),
                                              ))
                                        ]);
                                      }),
                                    )
                                  ]),
                            ),
                          ),
                          KembaliTombol()
                        ]),
                  ),
                ),
                Positioned(
                  left: 56.0,
                  top: 260.0,
                  right: null,
                  bottom: null,
                  width: 272.0,
                  height: 199.0,
                  child: Container(
                    width: 272.0,
                    height: 199.0,
                    child: ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Image.asset(
                        "assets/images/85bcf6f946a6ff1518928cc446791b8757454fef.png",
                        color: null,
                        fit: BoxFit.cover,
                        width: 272.0,
                        height: 199.0,
                        colorBlendMode: BlendMode.dstATop,
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: 114.0,
                  top: 475.0,
                  right: null,
                  bottom: null,
                  width: 159.0,
                  height: 23.0,
                  child: Text(
                    '''kelas tidak ditemukan''',
                    overflow: TextOverflow.visible,
                    textAlign: TextAlign.left,
                    style: TextStyle(
                      height: 1.5,
                      fontSize: 14.0,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w500,
                      color: Color.fromARGB(255, 120, 120, 120),

                      /* letterSpacing: 0.0, */
                    ),
                  ),
                )
              ]),
        ),
      )),
    );
  }
}
