import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutterapp/bloc/user_bloc.dart';
import 'package:flutterapp/component/InputField.dart';
import 'package:flutterapp/helpers/mask/mask.dart';
import 'package:flutterapp/helpers/svg/svg.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

import '../component/Alert.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class Login extends StatelessWidget {
  TextEditingController _emailController = TextEditingController();
  TextEditingController _passController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    UserBloc ub = context.read<UserBloc>();
    return Material(
        child: ClipRRect(
            borderRadius: BorderRadius.zero,
            child: SingleChildScrollView(
              child: Container(
                width: MediaQuery.of(context).size.width,
                height: 990.0,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    clipBehavior: Clip.none,
                    children: [
                      ClipRRect(
                        borderRadius: BorderRadius.zero,
                        child: Container(
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      Positioned(
                        left: -92.0,
                        top: -94.0,
                        right: null,
                        bottom: null,
                        width: MediaQuery.of(context).size.width,
                        height: 638.0,
                        child: Container(
                          width: MediaQuery.of(context).size.width,
                          height: 638.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              clipBehavior: Clip.none,
                              children: [
                                Positioned(
                                  left: 0.0,
                                  top: 0.0,
                                  right: null,
                                  bottom: null,
                                  width: MediaQuery.of(context).size.width,
                                  height: 638.0,
                                  child: Mask.fromSVGPath(
                                    'M574 319C574 495.179 445.506 638 287 638C128.494 638 0 495.179 0 319C0 142.821 128.494 0 287 0C445.506 0 574 142.821 574 319Z',
                                    child: Stack(
                                        fit: StackFit.expand,
                                        alignment: Alignment.center,
                                        clipBehavior: Clip.none,
                                        children: [
                                          Positioned(
                                            left: -116.2430419921875,
                                            top: -285.13970947265625,
                                            right: null,
                                            bottom: null,
                                            width: 690.2430419921875,
                                            height: 945.4161376953125,
                                            child: Container(
                                              width: 690.2430419921875,
                                              height: 945.4161376953125,
                                              child: ClipRRect(
                                                borderRadius: BorderRadius.zero,
                                                child: Image.asset(
                                                  "assets/images/c963427706d1f6cefaa3c93b4c412c48f6678638.png",
                                                  color: null,
                                                  fit: BoxFit.cover,
                                                  width: 690.2430419921875,
                                                  height: 945.4161376953125,
                                                  colorBlendMode:
                                                      BlendMode.dstATop,
                                                ),
                                              ),
                                            ),
                                          )
                                        ]),
                                    offset: Offset(0.0, 0.0),
                                  ),
                                )
                              ]),
                        ),
                      ),
                      Positioned(
                        left: -92.0,
                        top: -94.0,
                        right: null,
                        bottom: null,
                        width: MediaQuery.of(context).size.width,
                        height: 638.0,
                        child: Container(
                          width: MediaQuery.of(context).size.width,
                          height: 638.0,
                          child: SvgWidget(painters: [
                            SvgPathPainter.fill()
                              ..addPath(
                                  'M574 319C574 495.179 445.506 638 287 638C128.494 638 0 495.179 0 319C0 142.821 128.494 0 287 0C445.506 0 574 142.821 574 319Z')
                              ..color = Color.fromARGB(76, 29, 29, 29)
                              ..setBlur(2.0),
                          ]),
                        ),
                      ),
                      Positioned(
                        left: 0.0,
                        top: 337.0,
                        right: null,
                        bottom: null,
                        width: MediaQuery.of(context).size.width,
                        height: 507.0,
                        child: Container(
                          width: MediaQuery.of(context).size.width,
                          height: 507.0,
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(20.0),
                              topRight: Radius.circular(20.0),
                              bottomRight: Radius.circular(0.0),
                              bottomLeft: Radius.circular(0.0),
                            ),
                          ),
                          child: ClipRRect(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(20.0),
                              topRight: Radius.circular(20.0),
                              bottomRight: Radius.circular(0.0),
                              bottomLeft: Radius.circular(0.0),
                            ),
                            child: Container(
                              color: Color.fromARGB(255, 255, 255, 255),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20.0,
                        top: 360.0,
                        right: null,
                        bottom: null,
                        width: MediaQuery.of(context).size.width,
                        height: 59.0,
                        child: Container(
                          width: MediaQuery.of(context).size.width,
                          height: 59.0,
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(0.0),
                          ),
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              clipBehavior: Clip.none,
                              children: [
                                Positioned(
                                  left: 0.0,
                                  top: 0.0,
                                  right: null,
                                  bottom: null,
                                  width: MediaQuery.of(context).size.width,
                                  height: 36.0,
                                  child: Text(
                                    '''Login Akun''',
                                    overflow: TextOverflow.visible,
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      height: 1.26000001695421,
                                      fontSize: 27.0,
                                      fontFamily: 'Outfit',
                                      fontWeight: FontWeight.w600,
                                      color: Color.fromARGB(255, 42, 42, 42),

                                      /* letterSpacing: 0.54, */
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 42.0,
                                  right: null,
                                  bottom: null,
                                  width: MediaQuery.of(context).size.width,
                                  height: 19.0,
                                  child: Text(
                                    '''Hallo, Selamat Datang Kembali''',
                                    overflow: TextOverflow.visible,
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      height: 1.2102272851126534,
                                      fontSize: 14.0,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      color: Color.fromARGB(255, 120, 120, 120),

                                      /* letterSpacing: 0.28, */
                                    ),
                                  ),
                                )
                              ]),
                        ),
                      ),
                      Positioned(
                        left: 73.0,
                        top: 801.0,
                        right: null,
                        bottom: null,
                        width: 245.0,
                        height: 23.0,
                        child: GestureDetector(
                          onTap: () {
                            Navigator.pushNamed(context, '/Register');
                          },
                          child: RichText(
                              overflow: TextOverflow.visible,
                              textAlign: TextAlign.left,
                              text: const TextSpan(
                                style: TextStyle(
                                  height: 1.5,
                                  fontSize: 14.0,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w400,
                                  color: Color.fromARGB(255, 120, 120, 120),

                                  /* letterSpacing: 0.28, */
                                ),
                                children: [
                                  TextSpan(
                                    text: '''Tidak Memiliki Akun? ''',
                                    style: TextStyle(
                                      fontSize: 14.0,

                                      /* letterSpacing: null, */
                                    ),
                                  ),
                                  TextSpan(
                                    text: '''Daftar Disini''',
                                    style: TextStyle(
                                      fontSize: 14.0,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w600,
                                      color: Color.fromARGB(204, 47, 115, 254),

                                      /* letterSpacing: null, */
                                    ),
                                  )
                                ],
                              )),
                        ),
                      ),
                      Positioned(
                        left: 200.0,
                        top: 695.0,
                        right: null,
                        bottom: null,
                        width: 127.0,
                        height: 23.0,
                        child: GestureDetector(
                          onTap: () {
                            Navigator.pushNamed(context, '/ForgotPass');
                          },
                          child: Text(
                            '''Lupa Kata Sandi?''',
                            overflow: TextOverflow.visible,
                            textAlign: TextAlign.left,
                            style: TextStyle(
                              height: 1.5,
                              fontSize: 14.0,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w400,
                              color: Color.fromARGB(255, 120, 120, 120),

                              /* letterSpacing: 0.28, */
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 32.0,
                        top: 531.0,
                        right: null,
                        bottom: null,
                        width: 325.0,
                        height: 18.0,
                        child: Container(
                          width: 325.0,
                          height: 18.0,
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(0.0),
                          ),
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              clipBehavior: Clip.none,
                              children: [
                                Positioned(
                                  left: 0.0,
                                  top: 11.0,
                                  right: null,
                                  bottom: null,
                                  width: 131.0,
                                  height: 2.0,
                                  child: Container(
                                    width: 131.0,
                                    height: 2.0,
                                    child: SvgWidget(painters: [
                                      SvgPathPainter.stroke(
                                        2.0,
                                        strokeJoin: StrokeJoin.miter,
                                      )
                                        ..addPath('M0 0L131 0L131 -2L0 -2L0 0Z')
                                        ..color =
                                            Color.fromARGB(51, 120, 120, 120),
                                    ]),
                                  ),
                                ),
                                Positioned(
                                  left: 194.0,
                                  top: 11.0,
                                  right: null,
                                  bottom: null,
                                  width: 131.0,
                                  height: 2.0,
                                  child: Container(
                                    width: 131.0,
                                    height: 2.0,
                                    child: SvgWidget(painters: [
                                      SvgPathPainter.stroke(
                                        2.0,
                                        strokeJoin: StrokeJoin.miter,
                                      )
                                        ..addPath('M0 0L131 0L131 -2L0 -2L0 0Z')
                                        ..color =
                                            Color.fromARGB(51, 120, 120, 120),
                                    ]),
                                  ),
                                ),
                                Positioned(
                                  left: 147.0,
                                  top: 0.0,
                                  right: null,
                                  bottom: null,
                                  width: 36.0,
                                  height: 23.0,
                                  child: Text(
                                    '''Atau''',
                                    overflow: TextOverflow.visible,
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      height: 1.2599999564034599,
                                      fontSize: 14.0,
                                      fontFamily: 'Outfit',
                                      fontWeight: FontWeight.w300,
                                      color: Color.fromARGB(255, 42, 42, 42),

                                      /* letterSpacing: 0.28, */
                                    ),
                                  ),
                                )
                              ]),
                        ),
                      ),
                      Positioned(
                          left: 20.0,
                          top: 449.0,
                          right: null,
                          bottom: null,
                          width: MediaQuery.of(context).size.width * 0.9,
                          height: 50.0,
                          child: GestureDetector(
                            onTap: () {
                              Navigator.pushNamed(context, '/AkunGoogle');
                            },
                            child: Container(
                              width: MediaQuery.of(context).size.width * 0.9,
                              height: 50.0,
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  clipBehavior: Clip.none,
                                  children: [
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: 0.0,
                                      bottom: 0.0,
                                      width: null,
                                      height: null,
                                      child: LayoutBuilder(builder:
                                          (BuildContext context,
                                              BoxConstraints constraints) {
                                        final double width =
                                            constraints.maxWidth;

                                        final double height =
                                            constraints.maxHeight;

                                        return Stack(children: [
                                          TransformHelper.translate(
                                              x: 0,
                                              y: 0,
                                              z: 0,
                                              child: Container(
                                                width: width,
                                                height: height,
                                                child: Container(
                                                  width: MediaQuery.of(context)
                                                          .size
                                                          .width *
                                                      0.95,
                                                  height: 50.0,
                                                  decoration: BoxDecoration(
                                                    borderRadius:
                                                        BorderRadius.circular(
                                                            10.0),
                                                  ),
                                                  child: ClipRRect(
                                                    borderRadius:
                                                        BorderRadius.circular(
                                                            10.0),
                                                    child: Container(
                                                      color: Color.fromARGB(
                                                          255, 47, 115, 254),
                                                    ),
                                                  ),
                                                ),
                                              ))
                                        ]);
                                      }),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: 0.0,
                                      bottom: 0.0,
                                      width: null,
                                      height: null,
                                      child: LayoutBuilder(builder:
                                          (BuildContext context,
                                              BoxConstraints constraints) {
                                        final double width =
                                            constraints.maxWidth *
                                                0.12857142857142856;

                                        final double height =
                                            constraints.maxHeight * 0.78;

                                        return Stack(children: [
                                          TransformHelper.translate(
                                              x: constraints.maxWidth * 0.02,
                                              y: constraints.maxHeight * 0.12,
                                              z: 0,
                                              child: Container(
                                                width: width,
                                                height: height,
                                                child: Container(
                                                  width: MediaQuery.of(context)
                                                      .size
                                                      .width,
                                                  height: 39.0,
                                                  decoration: BoxDecoration(
                                                    borderRadius:
                                                        BorderRadius.circular(
                                                            8.0),
                                                  ),
                                                  child: ClipRRect(
                                                    borderRadius:
                                                        BorderRadius.circular(
                                                            8.0),
                                                    child: Container(
                                                      color: Color.fromARGB(
                                                          255, 255, 255, 255),
                                                    ),
                                                  ),
                                                ),
                                              ))
                                        ]);
                                      }),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: 0.0,
                                      bottom: 0.0,
                                      width: null,
                                      height: null,
                                      child: LayoutBuilder(builder:
                                          (BuildContext context,
                                              BoxConstraints constraints) {
                                        final double width =
                                            constraints.maxWidth *
                                                0.5085714285714286;

                                        final double height =
                                            constraints.maxHeight * 0.4;

                                        return Stack(children: [
                                          TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.19428571428571428,
                                            y: constraints.maxHeight * 0.32,
                                            z: 0,
                                            child: GestureDetector(
                                                onTap: () {
                                                  Navigator.pushNamed(
                                                      context, '/AkunGoogle');
                                                },
                                                child: Container(
                                                  width: width,
                                                  height: height,
                                                  child: Text(
                                                    '''Login Dengan Akun Google''',
                                                    overflow:
                                                        TextOverflow.visible,
                                                    textAlign: TextAlign.left,
                                                    style: TextStyle(
                                                      height:
                                                          1.2599999564034599,
                                                      fontSize: 13.0,
                                                      fontFamily: 'Outfit',
                                                      fontWeight:
                                                          FontWeight.w500,
                                                      color: Color.fromARGB(
                                                          255, 255, 255, 255),

                                                      /* letterSpacing: 0.28, */
                                                    ),
                                                  ),
                                                )),
                                          )
                                        ]);
                                      }),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: 0.0,
                                      bottom: 0.0,
                                      width: null,
                                      height: null,
                                      child: LayoutBuilder(builder:
                                          (BuildContext context,
                                              BoxConstraints constraints) {
                                        final double width =
                                            constraints.maxWidth *
                                                0.07142857142857142;

                                        final double height =
                                            constraints.maxHeight * 0.5;

                                        return Stack(children: [
                                          TransformHelper.translate(
                                              x: constraints.maxWidth *
                                                  0.04857142857142857,
                                              y: constraints.maxHeight * 0.26,
                                              z: 0,
                                              child: Container(
                                                width: width,
                                                height: height,
                                                child: ClipRRect(
                                                  borderRadius:
                                                      BorderRadius.zero,
                                                  child: Container(
                                                    width: 25.0,
                                                    height: 25.0,
                                                    child: Stack(
                                                        fit: StackFit.expand,
                                                        alignment:
                                                            Alignment.center,
                                                        clipBehavior: Clip.none,
                                                        children: [
                                                          Positioned(
                                                            left: 0.0,
                                                            top: 0.0,
                                                            right: 0.0,
                                                            bottom: 0.0,
                                                            width: null,
                                                            height: null,
                                                            child: LayoutBuilder(
                                                                builder: (BuildContext
                                                                        context,
                                                                    BoxConstraints
                                                                        constraints) {
                                                              double
                                                                  percentWidth =
                                                                  0.8333333587646484;
                                                              double scaleX = (constraints
                                                                          .maxWidth *
                                                                      percentWidth) /
                                                                  20.83333396911621;

                                                              double
                                                                  percentHeight =
                                                                  0.8333333587646484;
                                                              double scaleY = (constraints
                                                                          .maxHeight *
                                                                      percentHeight) /
                                                                  20.83333396911621;

                                                              return Stack(
                                                                  children: [
                                                                    TransformHelper.translateAndScale(
                                                                        translateX: constraints.maxWidth * 0.08333333015441895,
                                                                        translateY: constraints.maxHeight * 0.08333333015441895,
                                                                        translateZ: 0,
                                                                        scaleX: scaleX,
                                                                        scaleY: scaleY,
                                                                        scaleZ: 1,
                                                                        child: Container(
                                                                          width:
                                                                              20.83333396911621,
                                                                          height:
                                                                              20.83333396911621,
                                                                          child:
                                                                              SvgWidget(painters: [
                                                                            SvgPathPainter.fill()
                                                                              ..addPath('M20.6307 8.37656L19.7917 8.37656L19.7917 8.33333L10.4167 8.33333L10.4167 12.5L16.3036 12.5C15.4448 14.9255 13.137 16.6667 10.4167 16.6667C6.9651 16.6667 4.16667 13.8682 4.16667 10.4167C4.16667 6.9651 6.9651 4.16667 10.4167 4.16667C12.0099 4.16667 13.4594 4.76771 14.563 5.74948L17.5094 2.80313C15.649 1.06927 13.1604 0 10.4167 0C4.66406 0 0 4.66406 0 10.4167C0 16.1693 4.66406 20.8333 10.4167 20.8333C16.1693 20.8333 20.8333 16.1693 20.8333 10.4167C20.8333 9.71823 20.7615 9.03646 20.6307 8.37656Z')
                                                                              ..color = Color.fromARGB(255, 255, 193, 7),
                                                                          ]),
                                                                        ))
                                                                  ]);
                                                            }),
                                                          ),
                                                          Positioned(
                                                            left: 0.0,
                                                            top: 0.0,
                                                            right: 0.0,
                                                            bottom: 0.0,
                                                            width: null,
                                                            height: null,
                                                            child: LayoutBuilder(
                                                                builder: (BuildContext
                                                                        context,
                                                                    BoxConstraints
                                                                        constraints) {
                                                              double
                                                                  percentWidth =
                                                                  0.6523333740234375;
                                                              double scaleX = (constraints
                                                                          .maxWidth *
                                                                      percentWidth) /
                                                                  16.308334350585938;

                                                              double
                                                                  percentHeight =
                                                                  0.323125;
                                                              double scaleY =
                                                                  (constraints.maxHeight *
                                                                          percentHeight) /
                                                                      8.078125;

                                                              return Stack(
                                                                  children: [
                                                                    TransformHelper.translateAndScale(
                                                                        translateX: constraints.maxWidth * 0.13137500762939452,
                                                                        translateY: constraints.maxHeight * 0.08333333015441895,
                                                                        translateZ: 0,
                                                                        scaleX: scaleX,
                                                                        scaleY: scaleY,
                                                                        scaleZ: 1,
                                                                        child: Container(
                                                                          width:
                                                                              16.308334350585938,
                                                                          height:
                                                                              8.078125,
                                                                          child:
                                                                              SvgWidget(painters: [
                                                                            SvgPathPainter.fill()
                                                                              ..addPath('M0 5.56823L3.4224 8.07812C4.34844 5.78542 6.59115 4.16667 9.21563 4.16667C10.8089 4.16667 12.2583 4.76771 13.362 5.74948L16.3083 2.80312C14.4479 1.06927 11.9594 0 9.21563 0C5.21458 0 1.74479 2.25885 0 5.56823Z')
                                                                              ..color = Color.fromARGB(255, 255, 61, 0),
                                                                          ]),
                                                                        ))
                                                                  ]);
                                                            }),
                                                          ),
                                                          Positioned(
                                                            left: 0.0,
                                                            top: 0.0,
                                                            right: 0.0,
                                                            bottom: 0.0,
                                                            width: null,
                                                            height: null,
                                                            child: LayoutBuilder(
                                                                builder: (BuildContext
                                                                        context,
                                                                    BoxConstraints
                                                                        constraints) {
                                                              double
                                                                  percentWidth =
                                                                  0.6502916717529297;
                                                              double scaleX = (constraints
                                                                          .maxWidth *
                                                                      percentWidth) /
                                                                  16.257291793823242;

                                                              double
                                                                  percentHeight =
                                                                  0.3322083282470703;
                                                              double scaleY = (constraints
                                                                          .maxHeight *
                                                                      percentHeight) /
                                                                  8.305208206176758;

                                                              return Stack(
                                                                  children: [
                                                                    TransformHelper.translateAndScale(
                                                                        translateX: constraints.maxWidth * 0.1290625,
                                                                        translateY: constraints.maxHeight * 0.5844583511352539,
                                                                        translateZ: 0,
                                                                        scaleX: scaleX,
                                                                        scaleY: scaleY,
                                                                        scaleZ: 1,
                                                                        child: Container(
                                                                          width:
                                                                              16.257291793823242,
                                                                          height:
                                                                              8.305208206176758,
                                                                          child:
                                                                              SvgWidget(painters: [
                                                                            SvgPathPainter.fill()
                                                                              ..addPath('M9.27344 8.30521C11.9641 8.30521 14.4089 7.27552 16.2573 5.60104L13.0333 2.87292C11.9524 3.69499 10.6315 4.13962 9.27344 4.13854C6.56406 4.13854 4.26354 2.41094 3.39687 0L0 2.61719C1.72396 5.99062 5.225 8.30521 9.27344 8.30521Z')
                                                                              ..color = Color.fromARGB(255, 76, 175, 80),
                                                                          ]),
                                                                        ))
                                                                  ]);
                                                            }),
                                                          ),
                                                          Positioned(
                                                            left: 0.0,
                                                            top: 0.0,
                                                            right: 0.0,
                                                            bottom: 0.0,
                                                            width: null,
                                                            height: null,
                                                            child: LayoutBuilder(
                                                                builder: (BuildContext
                                                                        context,
                                                                    BoxConstraints
                                                                        constraints) {
                                                              double
                                                                  percentWidth =
                                                                  0.4166666793823242;
                                                              double scaleX = (constraints
                                                                          .maxWidth *
                                                                      percentWidth) /
                                                                  10.416666984558105;

                                                              double
                                                                  percentHeight =
                                                                  0.3922549819946289;
                                                              double scaleY = (constraints
                                                                          .maxHeight *
                                                                      percentHeight) /
                                                                  9.806374549865723;

                                                              return Stack(
                                                                  children: [
                                                                    TransformHelper.translateAndScale(
                                                                        translateX: constraints.maxWidth * 0.5,
                                                                        translateY: constraints.maxHeight * 0.4166666793823242,
                                                                        translateZ: 0,
                                                                        scaleX: scaleX,
                                                                        scaleY: scaleY,
                                                                        scaleZ: 1,
                                                                        child: Container(
                                                                          width:
                                                                              10.416666984558105,
                                                                          height:
                                                                              9.806374549865723,
                                                                          child:
                                                                              SvgWidget(painters: [
                                                                            SvgPathPainter.fill()
                                                                              ..addPath('M10.2141 0.0432293L9.375 0.0432293L9.375 0L0 0L0 4.16667L5.88698 4.16667C5.47615 5.32105 4.73612 6.32978 3.75833 7.06823L3.7599 7.06719L6.98385 9.79531C6.75573 10.0026 10.4167 7.29167 10.4167 2.08333C10.4167 1.3849 10.3448 0.703125 10.2141 0.0432293Z')
                                                                              ..color = Color.fromARGB(255, 25, 118, 210),
                                                                          ]),
                                                                        ))
                                                                  ]);
                                                            }),
                                                          )
                                                        ]),
                                                  ),
                                                ),
                                              ))
                                        ]);
                                      }),
                                    )
                                  ]),
                            ),
                          )),
                      Positioned(
                          left: 20.0,
                          top: 740.0,
                          right: null,
                          bottom: null,
                          width: MediaQuery.of(context).size.width * 0.9,
                          height: 45.0,
                          child: GestureDetector(
                            child: ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                width: MediaQuery.of(context).size.width * 0.9,
                                height: 45.0,
                                child: Stack(
                                    fit: StackFit.expand,
                                    alignment: Alignment.center,
                                    clipBehavior: Clip.none,
                                    children: [
                                      Positioned(
                                        left: 0.0,
                                        top: 0.0,
                                        right: 0.0,
                                        bottom: 0.0,
                                        width: null,
                                        height: null,
                                        child: LayoutBuilder(builder:
                                            (BuildContext context,
                                                BoxConstraints constraints) {
                                          final double width =
                                              constraints.maxWidth;

                                          final double height =
                                              constraints.maxHeight;

                                          return Stack(children: [
                                            TransformHelper.translate(
                                                x: 0,
                                                y: 0,
                                                z: 0,
                                                child: Container(
                                                  width: width,
                                                  height: height,
                                                  child: Container(
                                                    width:
                                                        MediaQuery.of(context)
                                                                .size
                                                                .width *
                                                            0.9,
                                                    height: 45.0,
                                                    decoration: BoxDecoration(
                                                      borderRadius:
                                                          BorderRadius.circular(
                                                              10.0),
                                                    ),
                                                    child: ClipRRect(
                                                      borderRadius:
                                                          BorderRadius.circular(
                                                              10.0),
                                                      child: Container(
                                                        color: Color.fromARGB(
                                                            255, 47, 115, 254),
                                                      ),
                                                    ),
                                                  ),
                                                ))
                                          ]);
                                        }),
                                      ),
                                      Positioned(
                                        left: 0.0,
                                        top: 0.0,
                                        right: 0.0,
                                        bottom: 0.0,
                                        width: null,
                                        height: null,
                                        child: LayoutBuilder(builder:
                                            (BuildContext context,
                                                BoxConstraints constraints) {
                                          final double width =
                                              constraints.maxWidth *
                                                  0.15428571428571428;

                                          final double height =
                                              constraints.maxHeight *
                                                  0.5333333333333333;

                                          return Stack(children: [
                                            TransformHelper.translate(
                                                x: constraints.maxWidth *
                                                    0.43142857142857144,
                                                y: constraints.maxHeight *
                                                    0.28888888888888886,
                                                z: 0,
                                                child: Container(
                                                  width: width,
                                                  height: height,
                                                  child: Text(
                                                    '''Masuk''',
                                                    overflow:
                                                        TextOverflow.visible,
                                                    textAlign: TextAlign.left,
                                                    style: TextStyle(
                                                      height:
                                                          1.3502273559570312,
                                                      fontSize: 14.0,
                                                      fontFamily: 'Poppins',
                                                      fontWeight:
                                                          FontWeight.w600,
                                                      color: Color.fromARGB(
                                                          255, 255, 255, 255),

                                                      /* letterSpacing: 0.28, */
                                                    ),
                                                  ),
                                                ))
                                          ]);
                                        }),
                                      )
                                    ]),
                              ),
                            ),
                            onTap: () {
                              if (_emailController.text == '' ||
                                  _passController.text == '') {
                                print('jalan');
                                showDialog<void>(
                                  context: context,
                                  builder: (context) => Alert(
                                    img: 'assets/images/email_pass_kosong.png',
                                    added: '',
                                    desc:
                                        'Isi semua form dengan data  diri anda pastikan data yang dimasukan sudah benar',
                                    title: 'Form Masih Kosong',
                                    titleButton: 'Kembali',
                                    addedFunc: () {},
                                    buttonFunc: () {
                                      Navigator.pop(context);
                                    },
                                  ),
                                );
                              } else if (_passController.text == 'salah') {
                                print('coba lagii');
                                showDialog<void>(
                                  context: context,
                                  builder: (context) => Alert(
                                    img: 'assets/images/email_pass_salah.png',
                                    added: '',
                                    desc:
                                        'Cek ulang password anda. Pastikan password dan konfirmasi password diisi sama.',
                                    title: 'Password Masih Salah',
                                    titleButton: 'Kembali',
                                    addedFunc: () {},
                                    buttonFunc: () {
                                      Navigator.pop(context);
                                    },
                                  ),
                                );
                              } else {
                                ub.changeEmail(_emailController.text);
                                Navigator.pushNamedAndRemoveUntil(
                                    context, '/Home', (route) => false);
                              }
                            },
                          )),
                      Positioned(
                          left: 20.0,
                          top: 581.0,
                          right: null,
                          bottom: null,
                          width: MediaQuery.of(context).size.width * 0.9,
                          height: 45.0,
                          child: InputField(
                            cont: _emailController,
                            hint: 'Masukkan email..',
                            obs: false,
                          )),
                      Positioned(
                          left: 20.0,
                          top: 642.0,
                          right: null,
                          bottom: null,
                          width: MediaQuery.of(context).size.width * 0.9,
                          height: 45.0,
                          child: InputField(
                            cont: _passController,
                            hint: 'Masukkan password',
                            obs: true,
                          ))
                    ]),
              ),
            )));
  }
}
