import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutterapp/bloc/kelas_bloc.dart';
import 'package:flutterapp/component/KembaliTombol.dart';
import 'package:flutterapp/component/ModalBottom.dart';
import 'package:flutterapp/component/Timer.dart';
import 'package:intl/intl.dart';
import '../bloc/order_bloc.dart';
import '../component/Alert.dart';
import '../component/CurrencyFormat.dart';
import '../helpers/mask/mask.dart';
import '../helpers/svg/svg.dart';
import '../helpers/transform/transform.dart';

/* Frame Detail Pembayaran 4
    Autogenerated by FlutLab FTF Generator
  */
class Pembayaran extends StatefulWidget {
  @override
  State<Pembayaran> createState() => _PembayaranState();
}

class _PembayaranState extends State<Pembayaran> {
  @override
  void initState() {
    super.initState();
    new Future.delayed(
        const Duration(seconds: 10),
        () => Navigator.pushNamed(context, '/Announcement', arguments: {
              'title': 'Pembayaran Berhasil',
              'desc':
                  'Yeyy, Kelas sudah aktif. siapkan semua keperluan untuk kelas',
              'img': 'assets/images/pembayaranberhasil.png',
              'titleButton': 'Home',
              'actButton': () {
                Navigator.pushNamed(context, '/Home');
              }
            }));
  }

  @override
  Widget build(BuildContext context) {
    OrderBloc ob = context.read<OrderBloc>();
    KelasBloc kb = context.read<KelasBloc>();
    String cdate1 = DateFormat("EEEEE, dd MMMM yyyy").format(DateTime.now());

    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                width: MediaQuery.of(context).size.width,
                height: 1080.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                          width: MediaQuery.of(context).size.width,
                          height: 844.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              clipBehavior: Clip.none,
                              children: [
                                ClipRRect(
                                  borderRadius: BorderRadius.zero,
                                  child: Container(
                                    color: Color.fromARGB(255, 255, 255, 255),
                                  ),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 92.0,
                                  right: null,
                                  bottom: null,
                                  width: MediaQuery.of(context).size.width,
                                  height: 188.0,
                                  child: Container(
                                    width: MediaQuery.of(context).size.width,
                                    height: 188.0,
                                    child: ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color:
                                            Color.fromARGB(255, 46, 115, 255),
                                      ),
                                    ),
                                  ),
                                ),
                                Positioned(
                                  left: 105.0,
                                  top: 120.0,
                                  right: null,
                                  bottom: null,
                                  width: 179.0,
                                  height: 132.0,
                                  child: Container(
                                    width: 179.0,
                                    height: 132.0,
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0.0),
                                    ),
                                    child: Stack(
                                        fit: StackFit.expand,
                                        alignment: Alignment.center,
                                        clipBehavior: Clip.none,
                                        children: [
                                          Positioned(
                                            left: 0.0,
                                            top: 0.0,
                                            right: null,
                                            bottom: null,
                                            width: 179.0,
                                            height: 69.0,
                                            child: Container(
                                              width: 179.0,
                                              height: 69.0,
                                              decoration: BoxDecoration(
                                                borderRadius:
                                                    BorderRadius.circular(0.0),
                                              ),
                                              child: Stack(
                                                  fit: StackFit.expand,
                                                  alignment: Alignment.center,
                                                  clipBehavior: Clip.none,
                                                  children: [
                                                    Positioned(
                                                        left: 0.0,
                                                        top: 0.0,
                                                        right: null,
                                                        bottom: null,
                                                        width: 181.0,
                                                        height: 45.0,
                                                        child:
                                                            CountdownTimerDemo()),
                                                    Positioned(
                                                      left: 5.0,
                                                      top: 51.0,
                                                      right: null,
                                                      bottom: null,
                                                      width: 165.0,
                                                      height: 18.0,
                                                      child: Container(
                                                        width: 165.0,
                                                        height: 18.0,
                                                        decoration:
                                                            BoxDecoration(
                                                          borderRadius:
                                                              BorderRadius
                                                                  .circular(
                                                                      0.0),
                                                        ),
                                                        child: Stack(
                                                            fit:
                                                                StackFit.expand,
                                                            alignment: Alignment
                                                                .center,
                                                            clipBehavior:
                                                                Clip.none,
                                                            children: [
                                                              Positioned(
                                                                left: 0.0,
                                                                top: 0.0,
                                                                right: null,
                                                                bottom: null,
                                                                width: 34.0,
                                                                height: 23.0,
                                                                child: Text(
                                                                  '''Jam''',
                                                                  overflow:
                                                                      TextOverflow
                                                                          .visible,
                                                                  textAlign:
                                                                      TextAlign
                                                                          .left,
                                                                  style:
                                                                      TextStyle(
                                                                    height:
                                                                        1.2599999564034599,
                                                                    fontSize:
                                                                        14.0,
                                                                    fontFamily:
                                                                        'Outfit',
                                                                    fontWeight:
                                                                        FontWeight
                                                                            .w500,
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            255,
                                                                            255,
                                                                            255),

                                                                    /* letterSpacing: 0.49000000000000005, */
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 71.0,
                                                                top: 0.0,
                                                                right: null,
                                                                bottom: null,
                                                                width: 33.0,
                                                                height: 23.0,
                                                                child: Text(
                                                                  '''Men''',
                                                                  overflow:
                                                                      TextOverflow
                                                                          .visible,
                                                                  textAlign:
                                                                      TextAlign
                                                                          .left,
                                                                  style:
                                                                      TextStyle(
                                                                    height:
                                                                        1.2599999564034599,
                                                                    fontSize:
                                                                        14.0,
                                                                    fontFamily:
                                                                        'Outfit',
                                                                    fontWeight:
                                                                        FontWeight
                                                                            .w500,
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            255,
                                                                            255,
                                                                            255),

                                                                    /* letterSpacing: 0.49000000000000005, */
                                                                  ),
                                                                ),
                                                              ),
                                                              Positioned(
                                                                left: 141.0,
                                                                top: 0.0,
                                                                right: null,
                                                                bottom: null,
                                                                width: 29.0,
                                                                height: 23.0,
                                                                child: Text(
                                                                  '''Det''',
                                                                  overflow:
                                                                      TextOverflow
                                                                          .visible,
                                                                  textAlign:
                                                                      TextAlign
                                                                          .left,
                                                                  style:
                                                                      TextStyle(
                                                                    height:
                                                                        1.2599999564034599,
                                                                    fontSize:
                                                                        14.0,
                                                                    fontFamily:
                                                                        'Outfit',
                                                                    fontWeight:
                                                                        FontWeight
                                                                            .w500,
                                                                    color: Color
                                                                        .fromARGB(
                                                                            255,
                                                                            255,
                                                                            255,
                                                                            255),

                                                                    /* letterSpacing: 0.49000000000000005, */
                                                                  ),
                                                                ),
                                                              )
                                                            ]),
                                                      ),
                                                    )
                                                  ]),
                                            ),
                                          ),
                                          Positioned(
                                            left: 3.0,
                                            top: 85.0,
                                            right: null,
                                            bottom: null,
                                            width: 173.0,
                                            height: 47.0,
                                            child: Container(
                                              width: 173.0,
                                              height: 47.0,
                                              decoration: BoxDecoration(
                                                borderRadius:
                                                    BorderRadius.circular(0.0),
                                              ),
                                              child: Stack(
                                                  fit: StackFit.expand,
                                                  alignment: Alignment.center,
                                                  clipBehavior: Clip.none,
                                                  children: [
                                                    Positioned(
                                                      left: 19.0,
                                                      top: 0.0,
                                                      right: null,
                                                      bottom: null,
                                                      width: 137.0,
                                                      height: 15.0,
                                                      child: Text(
                                                        '''Batas Akhir Pembayaran''',
                                                        overflow: TextOverflow
                                                            .visible,
                                                        textAlign:
                                                            TextAlign.center,
                                                        style: TextStyle(
                                                          height:
                                                              1.2102272727272727,
                                                          fontSize: 11.0,
                                                          fontFamily: 'Inter',
                                                          fontWeight:
                                                              FontWeight.w400,
                                                          color: Color.fromARGB(
                                                              255,
                                                              255,
                                                              255,
                                                              255),

                                                          /* letterSpacing: 0.385, */
                                                        ),
                                                      ),
                                                    ),
                                                    Positioned(
                                                      left: 0.0,
                                                      top: 29.0,
                                                      right: null,
                                                      bottom: null,
                                                      width: 200.0,
                                                      height: 20.0,
                                                      child: Text(
                                                        cdate1,
                                                        overflow: TextOverflow
                                                            .visible,
                                                        textAlign:
                                                            TextAlign.center,
                                                        style: TextStyle(
                                                          height:
                                                              1.2599999564034599,
                                                          fontSize: 14.0,
                                                          fontFamily: 'Outfit',
                                                          fontWeight:
                                                              FontWeight.w600,
                                                          color: Color.fromARGB(
                                                              255,
                                                              255,
                                                              255,
                                                              255),

                                                          /* letterSpacing: 0.49000000000000005, */
                                                        ),
                                                      ),
                                                    )
                                                  ]),
                                            ),
                                          )
                                        ]),
                                  ),
                                ),
                                Positioned(
                                  left: 17.0,
                                  top: 349.0,
                                  right: null,
                                  bottom: null,
                                  width: 355.0,
                                  height: 1.0,
                                  child: Container(
                                    width: 355.0,
                                    height: 1.0,
                                    child: SvgWidget(painters: [
                                      SvgPathPainter.stroke(
                                        1.0,
                                        strokeJoin: StrokeJoin.miter,
                                      )
                                        ..addPath('M0 0L355 0L355 -1L0 -1L0 0Z')
                                        ..color =
                                            Color.fromARGB(255, 225, 225, 225),
                                    ]),
                                  ),
                                ),
                                Positioned(
                                  left: 25.0,
                                  top: 365.0,
                                  right: null,
                                  bottom: null,
                                  width: 123.0,
                                  height: 39.0,
                                  child: Container(
                                    width: 123.0,
                                    height: 39.0,
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0.0),
                                    ),
                                    child: Stack(
                                        fit: StackFit.expand,
                                        alignment: Alignment.center,
                                        clipBehavior: Clip.none,
                                        children: [
                                          Positioned(
                                            left: 0.0,
                                            top: 21.0,
                                            right: null,
                                            bottom: null,
                                            width: 128.0,
                                            height: 23.0,
                                            child: Text(
                                              '''12415723325673''',
                                              overflow: TextOverflow.visible,
                                              textAlign: TextAlign.left,
                                              style: TextStyle(
                                                height: 1.2599999564034599,
                                                fontSize: 14.0,
                                                fontFamily: 'Outfit',
                                                fontWeight: FontWeight.w600,
                                                color: Color.fromARGB(
                                                    255, 0, 0, 0),

                                                /* letterSpacing: 1.61, */
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0.0,
                                            top: 0.0,
                                            right: null,
                                            bottom: null,
                                            width: 60.0,
                                            height: 15.0,
                                            child: Text(
                                              '''VA Number''',
                                              overflow: TextOverflow.visible,
                                              textAlign: TextAlign.left,
                                              style: TextStyle(
                                                height: 1.2102272727272727,
                                                fontSize: 11.0,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                                color: Color.fromARGB(
                                                    255, 87, 86, 86),

                                                /* letterSpacing: -0.16499999999999998, */
                                              ),
                                            ),
                                          )
                                        ]),
                                  ),
                                ),
                                Positioned(
                                  left: 25.0,
                                  top: 436.0,
                                  right: null,
                                  bottom: null,
                                  width: 208.0,
                                  height: 39.0,
                                  child: Container(
                                    width: 208.0,
                                    height: 39.0,
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0.0),
                                    ),
                                    child: Stack(
                                        fit: StackFit.expand,
                                        alignment: Alignment.center,
                                        clipBehavior: Clip.none,
                                        children: [
                                          Positioned(
                                            left: 0.0,
                                            top: 21.0,
                                            right: null,
                                            bottom: null,
                                            width: 213.0,
                                            height: 23.0,
                                            child: Text(
                                              '''APP-ON-LE39-AQ5-GUMV''',
                                              overflow: TextOverflow.visible,
                                              textAlign: TextAlign.left,
                                              style: TextStyle(
                                                height: 1.2599999564034599,
                                                fontSize: 14.0,
                                                fontFamily: 'Outfit',
                                                fontWeight: FontWeight.w600,
                                                color: Color.fromARGB(
                                                    255, 0, 0, 0),

                                                /* letterSpacing: 1.61, */
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0.0,
                                            top: 0.0,
                                            right: null,
                                            bottom: null,
                                            width: 59.0,
                                            height: 15.0,
                                            child: Text(
                                              '''ID Pesanan''',
                                              overflow: TextOverflow.visible,
                                              textAlign: TextAlign.left,
                                              style: TextStyle(
                                                height: 1.2102272727272727,
                                                fontSize: 11.0,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                                color: Color.fromARGB(
                                                    255, 87, 86, 86),

                                                /* letterSpacing: -0.16499999999999998, */
                                              ),
                                            ),
                                          )
                                        ]),
                                  ),
                                ),
                                Positioned(
                                  left: 17.0,
                                  top: 420.0,
                                  right: null,
                                  bottom: null,
                                  width: 355.0,
                                  height: 1.0,
                                  child: Container(
                                    width: 355.0,
                                    height: 1.0,
                                    child: SvgWidget(painters: [
                                      SvgPathPainter.stroke(
                                        1.0,
                                        strokeJoin: StrokeJoin.miter,
                                      )
                                        ..addPath('M0 0L355 0L355 -1L0 -1L0 0Z')
                                        ..color =
                                            Color.fromARGB(255, 225, 225, 225),
                                    ]),
                                  ),
                                ),

                                Positioned(
                                  left: 17.0,
                                  top: 491.0,
                                  right: null,
                                  bottom: null,
                                  width: 355.0,
                                  height: 1.0,
                                  child: Container(
                                    width: 355.0,
                                    height: 1.0,
                                    child: SvgWidget(painters: [
                                      SvgPathPainter.stroke(
                                        1.0,
                                        strokeJoin: StrokeJoin.miter,
                                      )
                                        ..addPath('M0 0L355 0L355 -1L0 -1L0 0Z')
                                        ..color =
                                            Color.fromARGB(255, 225, 225, 225),
                                    ]),
                                  ),
                                ),

                                Positioned(
                                  left: 17.0,
                                  top: 612.0,
                                  right: null,
                                  bottom: null,
                                  width: 355.0,
                                  height: 1.0,
                                  child: Container(
                                    width: 355.0,
                                    height: 1.0,
                                    child: SvgWidget(painters: [
                                      SvgPathPainter.stroke(
                                        1.0,
                                        strokeJoin: StrokeJoin.miter,
                                      )
                                        ..addPath('M0 0L355 0L355 -1L0 -1L0 0Z')
                                        ..color =
                                            Color.fromARGB(255, 225, 225, 225),
                                    ]),
                                  ),
                                ),

                                Positioned(
                                  left: 20.0,
                                  top: 578.0,
                                  right: null,
                                  bottom: null,
                                  width: 115.0,
                                  height: 20.0,
                                  child: Text(
                                    '''Cara Pembayaran''',
                                    overflow: TextOverflow.visible,
                                    textAlign: TextAlign.left,
                                    style: TextStyle(
                                      height: 1.2599999564034599,
                                      fontSize: 14.0,
                                      fontFamily: 'Outfit',
                                      fontWeight: FontWeight.w600,
                                      color: Color.fromARGB(255, 0, 0, 0),

                                      /* letterSpacing: -0.21, */
                                    ),
                                  ),
                                ),

                                Positioned(
                                  left: 22.0,
                                  top: 296.0,
                                  right: null,
                                  bottom: null,
                                  width: 216.0,
                                  height: 37.0,
                                  child: Container(
                                    width: 216.0,
                                    height: 37.0,
                                    child: Stack(
                                        fit: StackFit.expand,
                                        alignment: Alignment.center,
                                        clipBehavior: Clip.none,
                                        children: [
                                          Positioned(
                                            left: 60.0,
                                            top: 10.0,
                                            right: null,
                                            bottom: null,
                                            width: 200.0,
                                            height: 20.0,
                                            child: Text(
                                              ob.state['bank'],
                                              overflow: TextOverflow.visible,
                                              textAlign: TextAlign.left,
                                              style: TextStyle(
                                                height: 1.2102272033691406,
                                                fontSize: 15.0,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                                color: Color.fromARGB(
                                                    255, 0, 0, 0),

                                                /* letterSpacing: -0.22499999999999998, */
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0.0,
                                            top: 0.0,
                                            right: null,
                                            bottom: null,
                                            width: 44.0,
                                            height: 37.0,
                                            child: Container(
                                              width: 44.0,
                                              height: 37.0,
                                              child: ClipRRect(
                                                borderRadius: BorderRadius.zero,
                                                child: Image.asset(
                                                  ob.state['img'],
                                                  color: null,
                                                  fit: BoxFit.contain,
                                                  width: 44.0,
                                                  height: 37.0,
                                                  colorBlendMode:
                                                      BlendMode.dstATop,
                                                ),
                                              ),
                                            ),
                                          )
                                        ]),
                                  ),
                                ),

                                Positioned(
                                  left: 328.0,
                                  top: 447.0,
                                  right: null,
                                  bottom: null,
                                  width: 40.0,
                                  height: 23.0,
                                  child: GestureDetector(
                                    onTap: () => Navigator.pushNamed(
                                        context, '/DetailPembayaran'),
                                    child: Text(
                                      '''Lihat''',
                                      overflow: TextOverflow.visible,
                                      textAlign: TextAlign.left,
                                      style: TextStyle(
                                        height: 1.2599999564034599,
                                        fontSize: 14.0,
                                        fontFamily: 'Outfit',
                                        fontWeight: FontWeight.w500,
                                        color:
                                            Color.fromARGB(255, 46, 115, 255),

                                        /* letterSpacing: 0.49000000000000005, */
                                      ),
                                    ),
                                  ),
                                ),

                                Positioned(
                                  left: 25.0,
                                  top: 507.0,
                                  right: null,
                                  bottom: null,
                                  width: 97.0,
                                  height: 39.0,
                                  child: Container(
                                    width: 97.0,
                                    height: 39.0,
                                    decoration: BoxDecoration(
                                      borderRadius: BorderRadius.circular(0.0),
                                    ),
                                    child: Stack(
                                        fit: StackFit.expand,
                                        alignment: Alignment.center,
                                        clipBehavior: Clip.none,
                                        children: [
                                          Positioned(
                                            left: 0.0,
                                            top: 21.0,
                                            right: null,
                                            bottom: null,
                                            width: 99.0,
                                            height: 20.0,
                                            child: Text(
                                              '''Rp  ''' +
                                                  (CurrencyFormat()
                                                          .changeCurrency(ob
                                                                      .state[
                                                                  'transfer'] +
                                                              ob.state[
                                                                  'harga']))
                                                      .toString(),
                                              overflow: TextOverflow.visible,
                                              textAlign: TextAlign.left,
                                              style: TextStyle(
                                                height: 1.2599999564034599,
                                                fontSize: 14.0,
                                                fontFamily: 'Outfit',
                                                fontWeight: FontWeight.w600,
                                                color: Color.fromARGB(
                                                    255, 0, 0, 0),

                                                /* letterSpacing: 1.61, */
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0.0,
                                            top: 0.0,
                                            right: null,
                                            bottom: null,
                                            width: 120.0,
                                            height: 15.0,
                                            child: Text(
                                              '''Total Pembayaran''',
                                              overflow: TextOverflow.visible,
                                              textAlign: TextAlign.left,
                                              style: TextStyle(
                                                height: 1.2102272727272727,
                                                fontSize: 11.0,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                                color: Color.fromARGB(
                                                    255, 87, 86, 86),

                                                /* letterSpacing: -0.16499999999999998, */
                                              ),
                                            ),
                                          )
                                        ]),
                                  ),
                                ),
                                Positioned(
                                  left: 17.0,
                                  top: 562.0,
                                  right: null,
                                  bottom: null,
                                  width: 355.0,
                                  height: 1.0,
                                  child: Container(
                                    width: 355.0,
                                    height: 1.0,
                                    child: SvgWidget(painters: [
                                      SvgPathPainter.stroke(
                                        1.0,
                                        strokeJoin: StrokeJoin.miter,
                                      )
                                        ..addPath('M0 0L355 0L355 -1L0 -1L0 0Z')
                                        ..color =
                                            Color.fromARGB(255, 225, 225, 225),
                                    ]),
                                  ),
                                ),

                                //BRIMO
                                Positioned(
                                    // left: 31.0,
                                    top: 620.0,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 300.0,
                                    child: SingleChildScrollView(
                                      child: Column(
                                        children: [
                                          ExpansionTile(
                                              initiallyExpanded: true,
                                              title: Text(
                                                '''ATM BRI''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.2599999564034599,
                                                  fontSize: 14.0,
                                                  fontFamily: 'Outfit',
                                                  fontWeight: FontWeight.w600,
                                                  color: Color.fromARGB(
                                                      255, 0, 0, 0),

                                                  /* letterSpacing: 0.14, */
                                                ),
                                              ),
                                              children: [
                                                ListTile(
                                                    subtitle: Text(
                                                        '- Pilih menu transaksi lain \n- Pilih menu Pembayaran \n- Pilih menu Lainya \n- Pilih menu Briva \n- Masukan kode perusahaan : 90332 dan \n  nomor Handphone (contoh : 90332-098345345643) \n- Pilih Ya untuk proses pembayaran')),
                                              ]),
                                          ExpansionTile(
                                              title: Text(
                                                '''Brimo''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.2599999564034599,
                                                  fontSize: 14.0,
                                                  fontFamily: 'Outfit',
                                                  fontWeight: FontWeight.w600,
                                                  color: Color.fromARGB(
                                                      255, 0, 0, 0),

                                                  /* letterSpacing: 0.14, */
                                                ),
                                              ),
                                              children: [
                                                ListTile(
                                                    subtitle: Text(
                                                        '- Pilih menu transaksi lain \n- Pilih menu Pembayaran \n- Pilih menu Lainya \n- Pilih menu Briva \n- Masukan kode perusahaan : 90332 dan \n  nomor Handphone (contoh : 90332-098345345643) \n- Pilih Ya untuk proses pembayaran')),
                                              ]),
                                          ExpansionTile(
                                              title: Text(
                                                '''M-BAC''',
                                                overflow: TextOverflow.visible,
                                                textAlign: TextAlign.left,
                                                style: TextStyle(
                                                  height: 1.2599999564034599,
                                                  fontSize: 14.0,
                                                  fontFamily: 'Outfit',
                                                  fontWeight: FontWeight.w600,
                                                  color: Color.fromARGB(
                                                      255, 0, 0, 0),

                                                  /* letterSpacing: 0.14, */
                                                ),
                                              ),
                                              children: [
                                                ListTile(
                                                    subtitle: Text(
                                                        '- Pilih menu transaksi lain \n- Pilih menu Pembayaran \n- Pilih menu Lainya \n- Pilih menu Briva \n- Masukan kode perusahaan : 90332 dan \n  nomor Handphone (contoh : 90332-098345345643) \n- Pilih Ya untuk proses pembayaran')),
                                              ]),
                                        ],
                                      ),
                                    )),

                                //Appbar
                                Positioned(
                                  left: -42.0,
                                  top: 0.0,
                                  right: null,
                                  bottom: null,
                                  width: MediaQuery.of(context).size.width,
                                  height: 83.0,
                                  child: Container(
                                    width: MediaQuery.of(context).size.width,
                                    height: 83.0,
                                    child: Stack(
                                        fit: StackFit.expand,
                                        alignment: Alignment.center,
                                        clipBehavior: Clip.none,
                                        children: [
                                          Positioned(
                                            left: 42.0,
                                            top: 0.0,
                                            right: null,
                                            bottom: null,
                                            width: MediaQuery.of(context)
                                                .size
                                                .width,
                                            height: 83.0,
                                            child: Container(
                                              width: MediaQuery.of(context)
                                                  .size
                                                  .width,
                                              height: 83.0,
                                              child: ClipRRect(
                                                borderRadius: BorderRadius.zero,
                                                child: Container(
                                                  color: Color.fromARGB(
                                                      255, 255, 255, 255),
                                                ),
                                              ),
                                            ),
                                          ),
                                          Positioned(
                                            left: 0.0,
                                            top: 0.0,
                                            right: null,
                                            bottom: null,
                                            width: MediaQuery.of(context)
                                                .size
                                                .width,
                                            height: 76.00000762939453,
                                            child: Container(
                                              width: MediaQuery.of(context)
                                                  .size
                                                  .width,
                                              height: 76.00000762939453,
                                              child: Stack(
                                                  fit: StackFit.expand,
                                                  alignment: Alignment.center,
                                                  clipBehavior: Clip.none,
                                                  children: [
                                                    Positioned(
                                                      left: 172.0,
                                                      top: 54.0,
                                                      right: null,
                                                      bottom: null,
                                                      width: 125.0,
                                                      height: 21.0,
                                                      child: Text(
                                                        '''Detail Pembayaran''',
                                                        overflow: TextOverflow
                                                            .visible,
                                                        textAlign:
                                                            TextAlign.left,
                                                        style: TextStyle(
                                                          height:
                                                              1.3502273559570312,
                                                          fontSize: 14.0,
                                                          fontFamily: 'Outfit',
                                                          fontWeight:
                                                              FontWeight.w600,
                                                          color: Color.fromARGB(
                                                              255, 42, 42, 42),

                                                          /* letterSpacing: 0.0, */
                                                        ),
                                                      ),
                                                    ),
                                                  ]),
                                            ),
                                          )
                                        ]),
                                  ),
                                ),
                                KembaliTombol(),

                                //MBAC & Button
                              ]))),
                  Positioned(
                      left: 21.0,
                      top: 950.0,
                      right: null,
                      bottom: null,
                      width: MediaQuery.of(context).size.width * 0.9,
                      height: 45.0,
                      child: Center(
                        child: Container(
                          width: MediaQuery.of(context).size.width * 0.9,
                          height: 45.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              clipBehavior: Clip.none,
                              children: [
                                Positioned(
                                  left: 0.0,
                                  top: 0.0,
                                  right: 0.0,
                                  bottom: 0.0,
                                  width: null,
                                  height: null,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width = constraints.maxWidth;

                                    final double height = constraints.maxHeight;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                        x: 0,
                                        y: 0,
                                        z: 0,
                                        child: GestureDetector(
                                          onTap: () {
                                            showModalBottomSheet(
                                                context: context,
                                                builder:
                                                    (BuildContext context) {
                                                  return Confirm(
                                                      title:
                                                          'Apakah Anda Yakin Membatalkan?',
                                                      desc:
                                                          'Masih ada promo menarik untuk merasakan pengalaman belajar bersama psikologi terbaik',
                                                      titleButton1: 'Batal',
                                                      titleButton2: 'Tidak',
                                                      btnFunc1: () {
                                                        Navigator
                                                            .pushNamedAndRemoveUntil(
                                                                context,
                                                                '/Home',
                                                                (route) =>
                                                                    false);
                                                      },
                                                      btnFunc2: () {
                                                        Navigator.pop(context);
                                                      },
                                                      img:
                                                          'assets/images/batal_bayar.png');
                                                });
                                          },
                                          child: Container(
                                            width: width,
                                            height: height,
                                            child: Container(
                                              width: MediaQuery.of(context)
                                                      .size
                                                      .width *
                                                  0.9,
                                              height: 45.0,
                                              child: Stack(
                                                  fit: StackFit.expand,
                                                  alignment: Alignment.center,
                                                  clipBehavior: Clip.none,
                                                  children: [
                                                    Positioned(
                                                      left: 0.0,
                                                      top: 0.0,
                                                      right: 0.0,
                                                      bottom: 0.0,
                                                      width: null,
                                                      height: null,
                                                      child: LayoutBuilder(
                                                          builder: (BuildContext
                                                                  context,
                                                              BoxConstraints
                                                                  constraints) {
                                                        final double width =
                                                            constraints
                                                                .maxWidth;

                                                        final double height =
                                                            constraints
                                                                .maxHeight;

                                                        return Stack(children: [
                                                          TransformHelper
                                                              .translate(
                                                                  x: 0,
                                                                  y: 0,
                                                                  z: 0,
                                                                  child:
                                                                      Container(
                                                                    width:
                                                                        width,
                                                                    height:
                                                                        height,
                                                                    child:
                                                                        Container(
                                                                      width:
                                                                          350.0,
                                                                      height:
                                                                          45.0,
                                                                      decoration:
                                                                          BoxDecoration(
                                                                        borderRadius:
                                                                            BorderRadius.circular(10.0),
                                                                      ),
                                                                      child:
                                                                          ClipRRect(
                                                                        borderRadius:
                                                                            BorderRadius.circular(10.0),
                                                                        child: Container(
                                                                            color:
                                                                                Colors.red
                                                                            // Color.fromARGB(255, 47, 115, 254),
                                                                            ),
                                                                      ),
                                                                    ),
                                                                  ))
                                                        ]);
                                                      }),
                                                    ),
                                                    Positioned(
                                                      left: 0.0,
                                                      top: 0.0,
                                                      right: 0.0,
                                                      bottom: 0.0,
                                                      width: null,
                                                      height: null,
                                                      child: LayoutBuilder(
                                                          builder: (BuildContext
                                                                  context,
                                                              BoxConstraints
                                                                  constraints) {
                                                        final double width =
                                                            constraints
                                                                    .maxWidth *
                                                                0.12571428571428572;

                                                        final double height =
                                                            constraints
                                                                    .maxHeight *
                                                                0.5333333333333333;

                                                        return Stack(children: [
                                                          TransformHelper
                                                              .translate(
                                                                  x: constraints
                                                                          .maxWidth *
                                                                      0.4342857142857143,
                                                                  y: constraints
                                                                          .maxHeight *
                                                                      0.28888888888888886,
                                                                  z: 0,
                                                                  child:
                                                                      Container(
                                                                    width:
                                                                        width,
                                                                    height:
                                                                        height,
                                                                    child: Text(
                                                                      '''Batal''',
                                                                      overflow:
                                                                          TextOverflow
                                                                              .visible,
                                                                      textAlign:
                                                                          TextAlign
                                                                              .left,
                                                                      style:
                                                                          TextStyle(
                                                                        height:
                                                                            1.3502273559570312,
                                                                        fontSize:
                                                                            14.0,
                                                                        fontFamily:
                                                                            'Poppins',
                                                                        fontWeight:
                                                                            FontWeight.w600,
                                                                        color: Color.fromARGB(
                                                                            255,
                                                                            255,
                                                                            255,
                                                                            255),

                                                                        /* letterSpacing: 0.28, */
                                                                      ),
                                                                    ),
                                                                  ))
                                                        ]);
                                                      }),
                                                    )
                                                  ]),
                                            ),
                                          ),
                                        ),
                                      )
                                    ]);
                                  }),
                                )
                              ]),
                        ),
                      ))
                ])));
      }),
    ));
  }
}
