import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutterapp/bloc/agreement_bloc.dart';
import 'package:flutterapp/component/KembaliTombol.dart';
import '../bloc/bool_bloc.dart';
import '../component/Alert.dart';
import '../helpers/mask/mask.dart';
import '../helpers/svg/svg.dart';
import '../helpers/transform/transform.dart';

/* Frame Persetujuan
    Autogenerated by FlutLab FTF Generator
  */
class Persetujuan extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    AgreementBloc ab = context.read<AgreementBloc>();
    return Material(
      child: SingleChildScrollView(
          child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: MediaQuery.of(context).size.width * 0.9,
          height: 844.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              clipBehavior: Clip.none,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -39.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: 76.0,
                  child: Container(
                    width: MediaQuery.of(context).size.width,
                    height: 76.0,
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                            left: 167.0,
                            top: 54.0,
                            right: null,
                            bottom: null,
                            width: 114.0,
                            height: 21.0,
                            child: Text(
                              '''Form Persetujuan''',
                              overflow: TextOverflow.visible,
                              textAlign: TextAlign.justify,
                              style: TextStyle(
                                height: 1.3502273559570312,
                                fontSize: 14.0,
                                fontFamily: 'Outfit',
                                fontWeight: FontWeight.w600,
                                color: Color.fromARGB(255, 42, 42, 42),

                                /* letterSpacing: 0.0, */
                              ),
                            ),
                          ),
                        ]),
                  ),
                ),
                KembaliTombol(),
                Positioned(
                  left: 22.0,
                  top: 92.0,
                  right: null,
                  bottom: null,
                  width: 202.0,
                  height: 20.0,
                  child: Text(
                    '''Dengan ini saya menyatakan :''',
                    overflow: TextOverflow.visible,
                    textAlign: TextAlign.justify,
                    style: TextStyle(
                      height: 1.2599999564034599,
                      fontSize: 14.0,
                      fontFamily: 'Outfit',
                      fontWeight: FontWeight.w500,
                      color: Color.fromARGB(255, 0, 0, 0),

                      /* letterSpacing: 0.49000000000000005, */
                    ),
                  ),
                ),
                Positioned(
                  left: 22.0,
                  top: 131.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: 20.0,
                  child: Stack(
                      fit: StackFit.expand,
                      alignment: Alignment.center,
                      clipBehavior: Clip.none,
                      children: [
                        Positioned(
                          left: 0.0,
                          top: 0.0,
                          right: null,
                          bottom: null,
                          width: 19.6610164642334,
                          height: 20.0,
                          child: Container(
                            width: 19.6610164642334,
                            height: 20.0,
                            child: BlocBuilder<AgreementBloc, Map>(
                              buildWhen: (previous, current) {
                                if (current != previous) {
                                  return true;
                                } else {
                                  return false;
                                }
                              },
                              bloc: ab,
                              builder: (context, state) {
                                return Checkbox(
                                    value: state['cek1'],
                                    onChanged: (value) {
                                      ab.changeCek1(value!);
                                      return;
                                    });
                              },
                            ),
                          ),
                        ),
                        Positioned(
                          left: 36.0,
                          top: 4.0,
                          right: null,
                          bottom: null,
                          width: 155.0,
                          height: 15.0,
                          child: Text(
                            '''Berusia lebih dari 17 Tahun.''',
                            overflow: TextOverflow.visible,
                            textAlign: TextAlign.justify,
                            style: TextStyle(
                              height: 1.2102272727272727,
                              fontSize: 11.0,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              color: Color.fromARGB(255, 42, 42, 42),

                              /* letterSpacing: 0.385, */
                            ),
                          ),
                        ),
                      ]),
                ),
                Positioned(
                  left: 22.0,
                  top: 164.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: 26.0,
                  child: Container(
                    width: MediaQuery.of(context).size.width * 0.9,
                    height: 26.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(5.0),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: 19.6610164642334,
                            height: 20.0,
                            child: Container(
                              width: 19.6610164642334,
                              height: 20.0,
                              child: BlocBuilder<AgreementBloc, Map>(
                                buildWhen: (previous, current) {
                                  if (current != previous) {
                                    return true;
                                  } else {
                                    return false;
                                  }
                                },
                                bloc: ab,
                                builder: (context, state) {
                                  return Checkbox(
                                      value: state['cek2'],
                                      onChanged: (value) {
                                        ab.changeCek2(value!);
                                        return;
                                      });
                                },
                              ),
                            ),
                          ),
                          Positioned(
                            left: 35.38983154296875,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: MediaQuery.of(context).size.width * 0.9,
                            height: 28.0,
                            child: Text(
                              '''Bersedia mengikuti layanan edukasi tanpa adanya paksaan dari pihak manapun.''',
                              overflow: TextOverflow.visible,
                              textAlign: TextAlign.justify,
                              style: TextStyle(
                                height: 1.2102272727272727,
                                fontSize: 11.0,
                                fontFamily: 'Inter',
                                fontWeight: FontWeight.w400,
                                color: Color.fromARGB(255, 42, 42, 42),

                                /* letterSpacing: 0.385, */
                              ),
                            ),
                          ),
                        ]),
                  ),
                ),
                Positioned(
                  left: 22.0,
                  top: 274.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: 26.0,
                  child: Container(
                    width: MediaQuery.of(context).size.width * 0.9,
                    height: 26.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(5.0),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: MediaQuery.of(context).size.width * 0.9,
                            height: 26.0,
                            child: Container(
                              width: MediaQuery.of(context).size.width * 0.9,
                              height: 26.0,
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(5.0),
                              ),
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  clipBehavior: Clip.none,
                                  children: [
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 19.6610164642334,
                                      height: 20.0,
                                      child: Container(
                                        width: 19.6610164642334,
                                        height: 20.0,
                                        child: BlocBuilder<AgreementBloc, Map>(
                                          buildWhen: (previous, current) {
                                            if (current != previous) {
                                              return true;
                                            } else {
                                              return false;
                                            }
                                          },
                                          bloc: ab,
                                          builder: (context, state) {
                                            return Checkbox(
                                                value: state['cek3'],
                                                onChanged: (value) {
                                                  ab.changeCek3(value!);
                                                  return;
                                                });
                                          },
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 35.38983154296875,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: MediaQuery.of(context).size.width *
                                          0.9,
                                      height: 28.0,
                                      child: Text(
                                        '''Saat ini tidak sedang menyakiti atau membahayakan diri sendiri (selft-harm/suicidal attempts).''',
                                        overflow: TextOverflow.visible,
                                        textAlign: TextAlign.justify,
                                        style: TextStyle(
                                          height: 1.2102272727272727,
                                          fontSize: 11.0,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w400,
                                          color:
                                              Color.fromARGB(255, 42, 42, 42),

                                          /* letterSpacing: 0.385, */
                                        ),
                                      ),
                                    ),
                                  ]),
                            ),
                          )
                        ]),
                  ),
                ),
                Positioned(
                  left: 22.0,
                  top: 206.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: 52.0,
                  child: Container(
                    width: MediaQuery.of(context).size.width * 0.9,
                    height: 52.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(5.0),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: MediaQuery.of(context).size.width * 0.9,
                            height: 52.0,
                            child: Container(
                              width: MediaQuery.of(context).size.width * 0.9,
                              height: 52.0,
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(5.0),
                              ),
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  clipBehavior: Clip.none,
                                  children: [
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 19.6610164642334,
                                      height: 20.0,
                                      child: Container(
                                        width: 19.6610164642334,
                                        height: 20.0,
                                        child: BlocBuilder<AgreementBloc, Map>(
                                          buildWhen: (previous, current) {
                                            if (current != previous) {
                                              return true;
                                            } else {
                                              return false;
                                            }
                                          },
                                          bloc: ab,
                                          builder: (context, state) {
                                            return Checkbox(
                                                value: state['cek4'],
                                                onChanged: (value) {
                                                  ab.changeCek4(value!);
                                                  return;
                                                });
                                          },
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 35.38983154296875,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: MediaQuery.of(context).size.width *
                                          0.9,
                                      height: 54.0,
                                      child: Text(
                                        '''Memahami bahwa layanan edukasi yang diikuti terlingkup ke dalam beberapa kegiatan yaitu pemberian materi, konseling, pemberian terapi serta penegakan diagnosis.''',
                                        overflow: TextOverflow.visible,
                                        textAlign: TextAlign.justify,
                                        style: TextStyle(
                                          height: 1.2102272727272727,
                                          fontSize: 11.0,
                                          fontFamily: 'Inter',
                                          fontWeight: FontWeight.w400,
                                          color:
                                              Color.fromARGB(255, 42, 42, 42),

                                          /* letterSpacing: 0.385, */
                                        ),
                                      ),
                                    )
                                  ]),
                            ),
                          )
                        ]),
                  ),
                ),
                Positioned(
                  left: 22.0,
                  top: 316.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: 26.0,
                  child: Container(
                    width: MediaQuery.of(context).size.width * 0.9,
                    height: 26.0,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(5.0),
                    ),
                    child: Stack(
                        fit: StackFit.expand,
                        alignment: Alignment.center,
                        clipBehavior: Clip.none,
                        children: [
                          Positioned(
                            left: 0.0,
                            top: 0.0,
                            right: null,
                            bottom: null,
                            width: MediaQuery.of(context).size.width * 0.9,
                            height: 26.0,
                            child: Container(
                              width: MediaQuery.of(context).size.width * 0.9,
                              height: 26.0,
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(5.0),
                              ),
                              child: Stack(
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  clipBehavior: Clip.none,
                                  children: [
                                    Positioned(
                                      left: 0.0,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: 19.6610164642334,
                                      height: 20.0,
                                      child: Container(
                                        width: 19.6610164642334,
                                        height: 20.0,
                                        child: BlocBuilder<AgreementBloc, Map>(
                                          buildWhen: (previous, current) {
                                            if (current != previous) {
                                              return true;
                                            } else {
                                              return false;
                                            }
                                          },
                                          bloc: ab,
                                          builder: (context, state) {
                                            return Checkbox(
                                                value: state['cek5'],
                                                onChanged: (value) {
                                                  ab.changeCek5(value!);
                                                  return;
                                                });
                                          },
                                        ),
                                      ),
                                    ),
                                    Positioned(
                                      left: 35.38983154296875,
                                      top: 0.0,
                                      right: null,
                                      bottom: null,
                                      width: MediaQuery.of(context).size.width *
                                          0.9,
                                      height: 28.0,
                                      child: RichText(
                                          overflow: TextOverflow.visible,
                                          textAlign: TextAlign.justify,
                                          text: const TextSpan(
                                            style: TextStyle(
                                              height: 1.2599999687888406,
                                              fontSize: 11.0,
                                              fontFamily: 'Outfit',
                                              fontWeight: FontWeight.w300,
                                              color: Color.fromARGB(
                                                  255, 42, 42, 42),

                                              /* letterSpacing: 0.385, */
                                            ),
                                            children: [
                                              TextSpan(
                                                text:
                                                    '''Telah membaca serta menyetujui ''',
                                                style: TextStyle(
                                                  fontSize: 11.0,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  color: Color.fromARGB(
                                                      255, 42, 42, 42),

                                                  /* letterSpacing: null, */
                                                ),
                                              ),
                                              TextSpan(
                                                text:
                                                    '''syarat dan ketentuan ''',
                                                style: TextStyle(
                                                  fontSize: 11.0,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  color: Color.fromARGB(
                                                      255, 42, 42, 42),
                                                  decoration:
                                                      TextDecoration.underline,
                                                  /* letterSpacing: null, */
                                                ),
                                              ),
                                              TextSpan(
                                                text: '''yang diberikan.''',
                                                style: TextStyle(
                                                  fontSize: 11.0,
                                                  fontFamily: 'Inter',
                                                  fontWeight: FontWeight.w400,
                                                  color: Color.fromARGB(
                                                      255, 42, 42, 42),

                                                  /* letterSpacing: null, */
                                                ),
                                              )
                                            ],
                                          )),
                                    )
                                  ]),
                            ),
                          )
                        ]),
                  ),
                ),
                Positioned(
                  left: 20.0,
                  top: 733.0,
                  right: null,
                  bottom: null,
                  width: MediaQuery.of(context).size.width * 0.9,
                  height: 45.0,
                  child: ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: GestureDetector(
                        onTap: () {
                          ab.state['cek1'] == true &&
                                  ab.state['cek2'] == true &&
                                  ab.state['cek3'] == true &&
                                  ab.state['cek4'] == true &&
                                  ab.state['cek5'] == true
                              ? Navigator.pushNamed(context, '/DetailPesanan')
                              : showDialog<void>(
                                  context: context,
                                  builder: (context) => Alert(
                                    img: 'assets/images/email_pass_kosong.png',
                                    added: '',
                                    desc: 'Pastikan seluruh syarat terpenuhi',
                                    title: 'Syarat Belum Terpenuhi',
                                    titleButton: 'Kembali',
                                    addedFunc: () {},
                                    buttonFunc: () {
                                      Navigator.pop(context);
                                    },
                                  ),
                                );
                        },
                        child: Container(
                          width: MediaQuery.of(context).size.width * 0.9,
                          height: 45.0,
                          child: Stack(
                              fit: StackFit.expand,
                              alignment: Alignment.center,
                              clipBehavior: Clip.none,
                              children: [
                                Positioned(
                                  left: 0.0,
                                  top: 0.0,
                                  right: 0.0,
                                  bottom: 0.0,
                                  width: null,
                                  height: null,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width = constraints.maxWidth;

                                    final double height = constraints.maxHeight;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: 0,
                                          y: 0,
                                          z: 0,
                                          child: Container(
                                            width: width,
                                            height: height,
                                            child: Container(
                                              width: MediaQuery.of(context)
                                                      .size
                                                      .width *
                                                  0.9,
                                              height: 45.0,
                                              decoration: BoxDecoration(
                                                borderRadius:
                                                    BorderRadius.circular(10.0),
                                              ),
                                              child: ClipRRect(
                                                  borderRadius:
                                                      BorderRadius.circular(
                                                          10.0),
                                                  child: BlocBuilder<
                                                          AgreementBloc, Map>(
                                                      bloc: ab,
                                                      builder:
                                                          (context, state) {
                                                        return Container(
                                                          color: state[
                                                                          'cek1'] ==
                                                                      true &&
                                                                  state['cek2'] ==
                                                                      true &&
                                                                  state['cek3'] ==
                                                                      true &&
                                                                  state['cek4'] ==
                                                                      true &&
                                                                  state['cek5'] ==
                                                                      true
                                                              ? Color.fromARGB(
                                                                  255,
                                                                  47,
                                                                  115,
                                                                  254)
                                                              : Color.fromARGB(
                                                                  255,
                                                                  120,
                                                                  120,
                                                                  120),
                                                        );
                                                      })),
                                            ),
                                          ))
                                    ]);
                                  }),
                                ),
                                Positioned(
                                  left: 0.0,
                                  top: 0.0,
                                  right: 0.0,
                                  bottom: 0.0,
                                  width: null,
                                  height: null,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width = constraints.maxWidth *
                                        0.22285714285714286;

                                    final double height =
                                        constraints.maxHeight *
                                            0.5333333333333333;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: constraints.maxWidth *
                                              0.43142857142857144,
                                          y: constraints.maxHeight *
                                              0.28888888888888886,
                                          z: 0,
                                          child: Container(
                                            width: width,
                                            height: height,
                                            child: Text(
                                              '''Lanjutkan''',
                                              overflow: TextOverflow.visible,
                                              textAlign: TextAlign.justify,
                                              style: TextStyle(
                                                height: 1.3502273559570312,
                                                fontSize: 14.0,
                                                fontFamily: 'Poppins',
                                                fontWeight: FontWeight.w600,
                                                color: Color.fromARGB(
                                                    255, 255, 255, 255),

                                                /* letterSpacing: 0.28, */
                                              ),
                                            ),
                                          ))
                                    ]);
                                  }),
                                )
                              ]),
                        ),
                      )),
                )
              ]),
        ),
      )),
    );
  }
}
