import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutterapp/bloc/mindfull_bloc.dart';
import 'package:flutterapp/component/KembaliTombol.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import '../helpers/mask/mask.dart';
import '../helpers/svg/svg.dart';

/* Frame reading material
    Autogenerated by FlutLab FTF Generator
  */
class ReadingMindfull extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    MindfullBloc mb = context.read<MindfullBloc>();
    return Material(
      child: SingleChildScrollView(
          child: ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                height: 950.0,
                width: MediaQuery.of(context).size.width,
                child: Stack(
                    fit: StackFit.expand,
                    alignment: Alignment.center,
                    clipBehavior: Clip.none,
                    children: [
                      Container(
                        width: MediaQuery.of(context).size.width,
                        height: 844.0,
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            clipBehavior: Clip.none,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.zero,
                                child: Container(
                                  color: Color.fromARGB(255, 255, 255, 255),
                                ),
                              ),
                              Positioned(
                                left: 20.0,
                                top: 92.0,
                                right: null,
                                bottom: null,
                                width: 264.0,
                                height: 58.0,
                                child: Text(
                                  mb.state['title'],
                                  overflow: TextOverflow.visible,
                                  textAlign: TextAlign.left,
                                  style: TextStyle(
                                    height: 1.560227394104004,
                                    fontSize: 18.0,
                                    fontFamily: 'Outfit',
                                    fontWeight: FontWeight.w600,
                                    color: Color.fromARGB(255, 42, 42, 42),

                                    /* letterSpacing: 0.0, */
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 20.0,
                                top: 156.0,
                                right: null,
                                bottom: null,
                                width: 170.0,
                                height: 17.0,
                                child: RichText(
                                    overflow: TextOverflow.visible,
                                    textAlign: TextAlign.left,
                                    text: const TextSpan(
                                      style: TextStyle(
                                        height: 1.3502273559570312,
                                        fontSize: 11.0,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w500,
                                        color:
                                            Color.fromARGB(255, 120, 120, 120),

                                        /* letterSpacing: 0.0, */
                                      ),
                                      children: [
                                        TextSpan(
                                          text: '''Sept 20, 2022 by ''',
                                          style: TextStyle(
                                            fontFamily: 'Inter',
                                            fontWeight: FontWeight.w600,

                                            /* letterSpacing: null, */
                                          ),
                                        ),
                                        TextSpan(
                                          text: '''Agam Subekti''',
                                          style: TextStyle(
                                            fontFamily: 'Inter',
                                            fontWeight: FontWeight.w600,
                                            color: Color.fromARGB(
                                                255, 47, 115, 254),

                                            /* letterSpacing: null, */
                                          ),
                                        )
                                      ],
                                    )),
                              ),
                              Positioned(
                                left: 20.0,
                                top: 187.0,
                                right: null,
                                bottom: null,
                                width: MediaQuery.of(context).size.width * 0.9,
                                height: 180.0,
                                child: Container(
                                  width:
                                      MediaQuery.of(context).size.width * 0.9,
                                  height: 180.0,
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(20.0),
                                  ),
                                  child: Stack(
                                      fit: StackFit.expand,
                                      alignment: Alignment.center,
                                      clipBehavior: Clip.none,
                                      children: [
                                        Positioned(
                                          left: 0.0,
                                          top: 0.0,
                                          right: null,
                                          bottom: null,
                                          width: MediaQuery.of(context)
                                                  .size
                                                  .width *
                                              0.9,
                                          height: 180.0,
                                          child: Container(
                                            width: MediaQuery.of(context)
                                                    .size
                                                    .width *
                                                0.9,
                                            height: 180.0,
                                            decoration: BoxDecoration(
                                              borderRadius:
                                                  BorderRadius.circular(20.0),
                                            ),
                                            child: Stack(
                                                fit: StackFit.expand,
                                                alignment: Alignment.center,
                                                clipBehavior: Clip.none,
                                                children: [
                                                  Positioned(
                                                    left: 0.0,
                                                    top: 0.0,
                                                    right: null,
                                                    bottom: null,
                                                    width:
                                                        MediaQuery.of(context)
                                                                .size
                                                                .width *
                                                            0.9,
                                                    height: 180.0,
                                                    child: Mask.fromSVGPath(
                                                      'M0 20C0 8.9543 8.95431 0 20 0L328 0C339.046 0 348 8.95431 348 20L348 160C348 171.046 339.046 180 328 180L20 180C8.95431 180 0 171.046 0 160L0 20Z',
                                                      child: Stack(
                                                          fit: StackFit.expand,
                                                          alignment:
                                                              Alignment.center,
                                                          clipBehavior:
                                                              Clip.none,
                                                          children: [
                                                            Positioned(
                                                              left: 0.0,
                                                              top: 0.0,
                                                              right: null,
                                                              bottom: null,
                                                              width: MediaQuery.of(
                                                                          context)
                                                                      .size
                                                                      .width *
                                                                  0.9,
                                                              height: 180.0,
                                                              child: Container(
                                                                width: MediaQuery.of(
                                                                            context)
                                                                        .size
                                                                        .width *
                                                                    0.9,
                                                                height: 180.0,
                                                                decoration:
                                                                    BoxDecoration(
                                                                  borderRadius:
                                                                      BorderRadius
                                                                          .circular(
                                                                              20.0),
                                                                ),
                                                                child:
                                                                    ClipRRect(
                                                                  borderRadius:
                                                                      BorderRadius
                                                                          .circular(
                                                                              20.0),
                                                                  child: Image
                                                                      .asset(
                                                                    mb.state[
                                                                        'img'],
                                                                    color: null,
                                                                    fit: BoxFit
                                                                        .cover,
                                                                    width:
                                                                        348.0,
                                                                    height:
                                                                        180.0,
                                                                    colorBlendMode:
                                                                        BlendMode
                                                                            .dstATop,
                                                                  ),
                                                                ),
                                                              ),
                                                            )
                                                          ]),
                                                      offset: Offset(0.0, 0.0),
                                                    ),
                                                  )
                                                ]),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0.0,
                                          top: 0.0,
                                          right: null,
                                          bottom: null,
                                          width: MediaQuery.of(context)
                                                  .size
                                                  .width *
                                              0.9,
                                          height: 180.0,
                                          child: Container(
                                            width: MediaQuery.of(context)
                                                    .size
                                                    .width *
                                                0.9,
                                            height: 180.0,
                                            decoration: BoxDecoration(
                                              borderRadius:
                                                  BorderRadius.circular(20.0),
                                            ),
                                            child: ClipRRect(
                                              borderRadius:
                                                  BorderRadius.circular(20.0),
                                              child: Container(
                                                color: Color.fromARGB(
                                                    51, 42, 42, 42),
                                              ),
                                            ),
                                          ),
                                        )
                                      ]),
                                ),
                              ),
                              Positioned(
                                left: 24.0,
                                top: 383.0,
                                right: null,
                                bottom: null,
                                width: 126.0,
                                height: 40.0,
                                child: Container(
                                  width: 126.0,
                                  height: 40.0,
                                  child: Stack(
                                      fit: StackFit.expand,
                                      alignment: Alignment.center,
                                      clipBehavior: Clip.none,
                                      children: [
                                        Positioned(
                                          left: 0.0,
                                          top: 0.0,
                                          right: 0.0,
                                          bottom: 0.0,
                                          width: null,
                                          height: null,
                                          child: LayoutBuilder(builder:
                                              (BuildContext context,
                                                  BoxConstraints constraints) {
                                            final double width =
                                                constraints.maxWidth *
                                                    0.5555555555555556;

                                            final double height =
                                                constraints.maxHeight * 0.875;

                                            return Stack(children: [
                                              TransformHelper.translate(
                                                x: constraints.maxWidth *
                                                    0.4444444444444444,
                                                y: constraints.maxHeight *
                                                    0.075,
                                                z: 0,
                                                child: GestureDetector(
                                                    onTap: () {
                                                      Navigator.pushNamed(
                                                          context,
                                                          '/DetailPakar');
                                                    },
                                                    child: Container(
                                                      width: width,
                                                      height: height,
                                                      child: Container(
                                                        width: 70.0,
                                                        height: 35.0,
                                                        decoration:
                                                            BoxDecoration(
                                                          borderRadius:
                                                              BorderRadius
                                                                  .circular(
                                                                      0.0),
                                                        ),
                                                        child: Stack(
                                                            fit:
                                                                StackFit.expand,
                                                            alignment: Alignment
                                                                .center,
                                                            clipBehavior:
                                                                Clip.none,
                                                            children: [
                                                              Positioned(
                                                                left: 0.0,
                                                                top: 0.0,
                                                                right: 0.0,
                                                                bottom: 0.0,
                                                                width: null,
                                                                height: null,
                                                                child: LayoutBuilder(builder:
                                                                    (BuildContext
                                                                            context,
                                                                        BoxConstraints
                                                                            constraints) {
                                                                  final double
                                                                      width =
                                                                      constraints
                                                                              .maxWidth *
                                                                          0.9142857142857143;

                                                                  final double
                                                                      height =
                                                                      constraints
                                                                              .maxHeight *
                                                                          0.4;

                                                                  return Stack(
                                                                      children: [
                                                                        TransformHelper.translate(
                                                                            x: 0,
                                                                            y: constraints.maxHeight * 0.6571428571428571,
                                                                            z: 0,
                                                                            child: Container(
                                                                              width: width,
                                                                              height: height,
                                                                              child: Text(
                                                                                '''Sept 20, 2022''',
                                                                                overflow: TextOverflow.visible,
                                                                                textAlign: TextAlign.left,
                                                                                style: TextStyle(
                                                                                  height: 1.3502273559570312,
                                                                                  fontSize: 9.0,
                                                                                  fontFamily: 'Inter',
                                                                                  fontWeight: FontWeight.w600,
                                                                                  color: Color.fromARGB(255, 120, 120, 120),

                                                                                  /* letterSpacing: 0.0, */
                                                                                ),
                                                                              ),
                                                                            ))
                                                                      ]);
                                                                }),
                                                              ),
                                                              Positioned(
                                                                left: 0.0,
                                                                top: 0.0,
                                                                right: 0.0,
                                                                bottom: 0.0,
                                                                width: null,
                                                                height: null,
                                                                child: LayoutBuilder(builder:
                                                                    (BuildContext
                                                                            context,
                                                                        BoxConstraints
                                                                            constraints) {
                                                                  final double
                                                                      width =
                                                                      constraints
                                                                              .maxWidth *
                                                                          1.0285714285714285;

                                                                  final double
                                                                      height =
                                                                      constraints
                                                                              .maxHeight *
                                                                          0.4857142857142857;

                                                                  return Stack(
                                                                      children: [
                                                                        TransformHelper.translate(
                                                                            x: 0,
                                                                            y: 0,
                                                                            z: 0,
                                                                            child: Container(
                                                                              width: width,
                                                                              height: height,
                                                                              child: Text(
                                                                                '''Agam Subekti''',
                                                                                overflow: TextOverflow.visible,
                                                                                textAlign: TextAlign.left,
                                                                                style: TextStyle(
                                                                                  height: 1.3502273559570312,
                                                                                  fontSize: 11.0,
                                                                                  fontFamily: 'Outfit',
                                                                                  fontWeight: FontWeight.w600,
                                                                                  color: Color.fromARGB(255, 47, 115, 254),

                                                                                  /* letterSpacing: 0.0, */
                                                                                ),
                                                                              ),
                                                                            ))
                                                                      ]);
                                                                }),
                                                              )
                                                            ]),
                                                      ),
                                                    )),
                                              )
                                            ]);
                                          }),
                                        ),
                                        Positioned(
                                          left: 0.0,
                                          top: 0.0,
                                          right: 0.0,
                                          bottom: 0.0,
                                          width: null,
                                          height: null,
                                          child: LayoutBuilder(builder:
                                              (BuildContext context,
                                                  BoxConstraints constraints) {
                                            final double width =
                                                constraints.maxWidth *
                                                    0.31746031746031744;

                                            final double height =
                                                constraints.maxHeight;

                                            return Stack(children: [
                                              TransformHelper.translate(
                                                  x: 0,
                                                  y: 0,
                                                  z: 0,
                                                  child: Container(
                                                    width: width,
                                                    height: height,
                                                    child: Container(
                                                      width: 40.0,
                                                      height: 40.0,
                                                      child: Stack(
                                                          fit: StackFit.expand,
                                                          alignment:
                                                              Alignment.center,
                                                          clipBehavior:
                                                              Clip.none,
                                                          children: [
                                                            Positioned(
                                                              left: 0.0,
                                                              top: 0.0,
                                                              right: null,
                                                              bottom: null,
                                                              width: 40.0,
                                                              height: 40.0,
                                                              child: Mask
                                                                  .fromSVGPath(
                                                                'M40 20C40 31.0457 31.0457 40 20 40C8.9543 40 0 31.0457 0 20C0 8.9543 8.9543 0 20 0C31.0457 0 40 8.9543 40 20Z',
                                                                child: Stack(
                                                                    fit: StackFit
                                                                        .expand,
                                                                    alignment:
                                                                        Alignment
                                                                            .center,
                                                                    clipBehavior:
                                                                        Clip.none,
                                                                    children: [
                                                                      Positioned(
                                                                        left:
                                                                            0.0,
                                                                        top:
                                                                            0.0,
                                                                        right:
                                                                            0.0,
                                                                        bottom:
                                                                            0.0,
                                                                        width:
                                                                            null,
                                                                        height:
                                                                            null,
                                                                        child: LayoutBuilder(builder: (BuildContext
                                                                                context,
                                                                            BoxConstraints
                                                                                constraints) {
                                                                          final double
                                                                              width =
                                                                              constraints.maxWidth * 1.0666666984558106;

                                                                          final double
                                                                              height =
                                                                              constraints.maxHeight * 1.633333396911621;

                                                                          return Stack(
                                                                              children: [
                                                                                TransformHelper.translate(
                                                                                    x: constraints.maxWidth * -0.03333333432674408,
                                                                                    y: constraints.maxHeight * -0.06666666865348816,
                                                                                    z: 0,
                                                                                    child: Container(
                                                                                      width: width,
                                                                                      height: height,
                                                                                      child: Container(
                                                                                        width: 42.66666793823242,
                                                                                        height: 65.33333587646484,
                                                                                        child: ClipRRect(
                                                                                          borderRadius: BorderRadius.zero,
                                                                                          child: Image.asset(
                                                                                            "assets/images/4cf11158f4e93e7edc3a448dcd349b6a458e37e5.png",
                                                                                            color: null,
                                                                                            fit: BoxFit.cover,
                                                                                            width: 42.66666793823242,
                                                                                            height: 65.33333587646484,
                                                                                            colorBlendMode: BlendMode.dstATop,
                                                                                          ),
                                                                                        ),
                                                                                      ),
                                                                                    ))
                                                                              ]);
                                                                        }),
                                                                      )
                                                                    ]),
                                                                offset: Offset(
                                                                    0.0, 0.0),
                                                              ),
                                                            )
                                                          ]),
                                                    ),
                                                  ))
                                            ]);
                                          }),
                                        )
                                      ]),
                                ),
                              ),
                              Positioned(
                                left: 19.999996185302734,
                                top: 439.0,
                                right: null,
                                bottom: null,
                                width: MediaQuery.of(context).size.width * 0.9,
                                height: 400.0,
                                child: Container(
                                  width:
                                      MediaQuery.of(context).size.width * 0.9,
                                  height: 400.0,
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(0.0),
                                  ),
                                  child: Stack(
                                      fit: StackFit.expand,
                                      alignment: Alignment.center,
                                      clipBehavior: Clip.none,
                                      children: [
                                        Positioned(
                                          left: 0.000003584333853723365,
                                          top: 0.0,
                                          right: null,
                                          bottom: null,
                                          width: MediaQuery.of(context)
                                                  .size
                                                  .width *
                                              0.9,
                                          height: 92.0,
                                          child: Text(
                                            mb.state['desc1'],
                                            maxLines: 5,
                                            overflow: TextOverflow.visible,
                                            textAlign: TextAlign.justify,
                                            style: TextStyle(
                                              height: 1.625227321277965,
                                              fontSize: 11.0,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              color: Color.fromARGB(
                                                  255, 42, 42, 42),

                                              /* letterSpacing: 0.0, */
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0.000003584333853723365,
                                          top: 204.0,
                                          right: null,
                                          bottom: null,
                                          width: MediaQuery.of(context)
                                                  .size
                                                  .width *
                                              0.9,
                                          height: 92.0,
                                          child: Text(
                                            mb.state['desc3'],
                                            overflow: TextOverflow.visible,
                                            textAlign: TextAlign.justify,
                                            style: TextStyle(
                                              height: 1.625227321277965,
                                              fontSize: 11.0,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              color: Color.fromARGB(
                                                  255, 42, 42, 42),

                                              /* letterSpacing: 0.0, */
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 0.000003584333853723365,
                                          top: 106.0,
                                          right: null,
                                          bottom: null,
                                          width: 82.0,
                                          height: 3.0,
                                          child: TransformHelper.rotate(
                                              a: -0.00,
                                              b: -1.00,
                                              c: 1.00,
                                              d: -0.00,
                                              child: Container(
                                                width: 82.0,
                                                height: 3.0,
                                                child: SvgWidget(painters: [
                                                  SvgPathPainter.stroke(
                                                    3.0,
                                                    strokeJoin:
                                                        StrokeJoin.miter,
                                                  )
                                                    ..addPath(
                                                        'M0 0L82 0L82 -3L0 -3L0 0Z')
                                                    ..color = Color.fromARGB(
                                                        255, 50, 85, 123),
                                                ]),
                                              )),
                                        ),
                                        Positioned(
                                          left: 16.000003814697266,
                                          top: 111.0,
                                          right: null,
                                          bottom: null,
                                          width: MediaQuery.of(context)
                                                  .size
                                                  .width *
                                              0.85,
                                          height: 74.0,
                                          child: Text(
                                            mb.state['desc2'],
                                            maxLines: 5,
                                            overflow: TextOverflow.visible,
                                            textAlign: TextAlign.justify,
                                            style: TextStyle(
                                              height: 1.625227321277965,
                                              fontSize: 11.0,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              color:
                                                  Color.fromARGB(255, 0, 0, 0),

                                              /* letterSpacing: 0.0, */
                                            ),
                                          ),
                                        )
                                      ]),
                                ),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 780.0,
                                right: null,
                                bottom: null,
                                width: MediaQuery.of(context).size.width,
                                height: 64.0,
                                child: Container(
                                  width: MediaQuery.of(context).size.width,
                                  height: 64.0,
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.only(
                                      topLeft: Radius.circular(10.0),
                                      topRight: Radius.circular(10.0),
                                      bottomRight: Radius.circular(0.0),
                                      bottomLeft: Radius.circular(0.0),
                                    ),
                                    gradient: LinearGradient(
                                      begin: Alignment(1.9297297093601173e-10,
                                          0.9999999842058545),
                                      end: Alignment(-3.189957187288428e-10,
                                          -4.306122361502052),
                                      stops: [
                                        0.2098725587129593,
                                        0.47089698910713196
                                      ],
                                      colors: [
                                        Color.fromARGB(255, 255, 255, 255),
                                        Color.fromARGB(0, 255, 255, 255)
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 305.0,
                                top: 391.0,
                                right: null,
                                bottom: null,
                                width: 59.0,
                                height: 24.0,
                                child: Container(
                                  width: 59.0,
                                  height: 24.0,
                                  child: Stack(
                                      fit: StackFit.expand,
                                      alignment: Alignment.center,
                                      clipBehavior: Clip.none,
                                      children: [
                                        Positioned(
                                          left: 0.0,
                                          top: 3.0,
                                          right: null,
                                          bottom: null,
                                          width: 32.0,
                                          height: 24.0,
                                          child: Text(
                                            '''223''',
                                            overflow: TextOverflow.visible,
                                            textAlign: TextAlign.left,
                                            style: TextStyle(
                                              height: 1.3502273559570312,
                                              fontSize: 14.0,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w600,
                                              color: Color.fromARGB(
                                                  255, 50, 85, 123),

                                              /* letterSpacing: 0.0, */
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 35.0,
                                          top: 0.0,
                                          right: null,
                                          bottom: null,
                                          width: 24.0,
                                          height: 24.0,
                                          child: ClipRRect(
                                            borderRadius: BorderRadius.zero,
                                            child: Container(
                                              width: 24.0,
                                              height: 24.0,
                                              child: Stack(
                                                  fit: StackFit.expand,
                                                  alignment: Alignment.center,
                                                  clipBehavior: Clip.none,
                                                  children: [
                                                    Positioned(
                                                      left: 0.0,
                                                      top: 0.0,
                                                      right: 0.0,
                                                      bottom: 0.0,
                                                      width: null,
                                                      height: null,
                                                      child: LayoutBuilder(
                                                          builder: (BuildContext
                                                                  context,
                                                              BoxConstraints
                                                                  constraints) {
                                                        double percentWidth =
                                                            0.7513891855875651;
                                                        double scaleX = (constraints
                                                                    .maxWidth *
                                                                percentWidth) /
                                                            18.033340454101562;

                                                        double percentHeight =
                                                            0.8824768861134847;
                                                        double scaleY = (constraints
                                                                    .maxHeight *
                                                                percentHeight) /
                                                            21.179445266723633;

                                                        return Stack(children: [
                                                          TransformHelper
                                                              .translateAndScale(
                                                                  translateX: constraints
                                                                          .maxWidth *
                                                                      0.12241904934247334,
                                                                  translateY: constraints
                                                                          .maxHeight *
                                                                      0.041791667540868126,
                                                                  translateZ: 0,
                                                                  scaleX:
                                                                      scaleX,
                                                                  scaleY:
                                                                      scaleY,
                                                                  scaleZ: 1,
                                                                  child:
                                                                      Container(
                                                                    width:
                                                                        18.033340454101562,
                                                                    height:
                                                                        21.179445266723633,
                                                                    child: SvgWidget(
                                                                        painters: [
                                                                          SvgPathPainter
                                                                              .fill()
                                                                            ..addPath('M12.1179 8.001C12.5779 6.574 12.8109 5.324 12.8109 4.247C12.8109 1.849 11.8719 0 10.3109 0C9.46394 0 9.20194 0.504 8.87394 1.747C8.89194 1.682 8.71094 2.381 8.65894 2.568C8.55794 2.927 8.38194 3.538 8.13194 4.399C8.12515 4.42201 8.11505 4.4439 8.10194 4.464L5.23594 8.95C4.55761 10.0108 3.55693 10.8261 2.38094 11.276L1.12394 11.758C0.739735 11.9052 0.419674 12.183 0.219971 12.5428C0.0202684 12.9025 -0.0463052 13.3211 0.0319428 13.725L0.717943 17.264C0.79978 17.6861 1.00085 18.0759 1.29735 18.3873C1.59384 18.6987 1.97335 18.9186 2.39094 19.021L10.6409 21.043C11.857 21.3409 13.1416 21.1467 14.2152 20.5025C15.2888 19.8583 16.0646 18.8162 16.3739 17.603L17.9479 11.43C18.0516 11.0239 18.061 10.5996 17.9756 10.1893C17.8901 9.77901 17.712 9.39369 17.4549 9.06276C17.1978 8.73183 16.8684 8.46404 16.492 8.27985C16.1156 8.09566 15.702 7.99994 15.2829 8L12.1179 8L12.1179 8.001Z')
                                                                            ..color = Color.fromARGB(
                                                                                255,
                                                                                47,
                                                                                115,
                                                                                254),
                                                                        ]),
                                                                  ))
                                                        ]);
                                                      }),
                                                    )
                                                  ]),
                                            ),
                                          ),
                                        )
                                      ]),
                                ),
                              ),
                              Positioned(
                                left: 0.0,
                                top: 0.0,
                                right: null,
                                bottom: null,
                                width: MediaQuery.of(context).size.width,
                                height: 83.0,
                                child: Container(
                                  width: MediaQuery.of(context).size.width,
                                  height: 83.0,
                                  child: ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 164.0,
                                top: 54.0,
                                right: null,
                                bottom: null,
                                width: 57.0,
                                height: 24.0,
                                child: Text(
                                  '''Mindfull''',
                                  overflow: TextOverflow.visible,
                                  textAlign: TextAlign.left,
                                  style: TextStyle(
                                    height: 1.3502273559570312,
                                    fontSize: 14.0,
                                    fontFamily: 'Outfit',
                                    fontWeight: FontWeight.w600,
                                    color: Color.fromARGB(255, 42, 42, 42),

                                    /* letterSpacing: 0.0, */
                                  ),
                                ),
                              )
                            ]),
                      ),
                      KembaliTombol(),
                      Positioned(
                        left: 0.0,
                        top: 0.0,
                        right: 0.0,
                        bottom: 0.0,
                        width: null,
                        height: null,
                        child: LayoutBuilder(builder:
                            (BuildContext context, BoxConstraints constraints) {
                          final double width =
                              constraints.maxWidth * 0.0641025641025641;

                          final double height =
                              constraints.maxHeight * 0.02962085308056872;

                          return Stack(children: [
                            TransformHelper.translate(
                                x: constraints.maxWidth * 0.8794871794871795,
                                y: constraints.maxHeight * 0.06042654028436019,
                                z: 0,
                                child: Container(
                                  width: width,
                                  height: height,
                                  child: ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      width: 25.0,
                                      height: 25.0,
                                      child: Stack(
                                          fit: StackFit.expand,
                                          alignment: Alignment.center,
                                          clipBehavior: Clip.none,
                                          children: [
                                            Positioned(
                                              left: 0.0,
                                              top: 0.0,
                                              right: 0.0,
                                              bottom: 0.0,
                                              width: null,
                                              height: null,
                                              child: LayoutBuilder(builder:
                                                  (BuildContext context,
                                                      BoxConstraints
                                                          constraints) {
                                                double percentWidth = 0.75;
                                                double scaleX =
                                                    (constraints.maxWidth *
                                                            percentWidth) /
                                                        18.75;

                                                double percentHeight = 0.71875;
                                                double scaleY =
                                                    (constraints.maxHeight *
                                                            percentHeight) /
                                                        17.96875;

                                                return Stack(children: [
                                                  TransformHelper
                                                      .translateAndScale(
                                                          translateX: constraints
                                                                  .maxWidth *
                                                              0.125,
                                                          translateY: constraints
                                                                  .maxHeight *
                                                              0.125,
                                                          translateZ: 0,
                                                          scaleX: scaleX,
                                                          scaleY: scaleY,
                                                          scaleZ: 1,
                                                          child: Container(
                                                            width: 18.75,
                                                            height: 17.96875,
                                                            child: SvgWidget(
                                                                painters: [
                                                                  SvgPathPainter
                                                                      .fill()
                                                                    ..addPath(
                                                                        'M9.375 0C7.7 0 6.34062 1.34375 6.27344 3.00312C4.8729 3.60157 3.67942 4.59892 2.84172 5.87089C2.00402 7.14286 1.55914 8.63321 1.5625 10.1562C1.5625 10.2891 1.55625 10.4375 1.5625 10.5961C0.636719 11.1398 0 12.1367 0 13.2812C0 14.9977 1.40859 16.4062 3.125 16.4062C3.57422 16.4062 4.00781 16.3109 4.39453 16.1375C5.74844 17.275 7.51406 17.9688 9.375 17.9688C11.2359 17.9688 13.0016 17.275 14.3555 16.1375C14.755 16.3154 15.1876 16.4069 15.625 16.4062C17.3414 16.4062 18.75 14.9977 18.75 13.2812C18.75 12.125 18.1055 11.1117 17.1641 10.5703C17.1758 10.4453 17.1875 10.3203 17.1875 10.1562C17.1911 8.63317 16.7463 7.14273 15.9085 5.87072C15.0708 4.59871 13.8772 3.6014 12.4766 3.00312C12.4086 1.34375 11.0492 0 9.375 0ZM9.375 1.5625C10.2469 1.5625 10.9375 2.25312 10.9375 3.125C10.9375 3.99688 10.2469 4.6875 9.375 4.6875C8.50313 4.6875 7.8125 3.99688 7.8125 3.125C7.8125 2.25312 8.50313 1.5625 9.375 1.5625ZM6.61719 4.56562C7.14062 5.56094 8.17969 6.25 9.375 6.25C10.5703 6.25 11.6094 5.56094 12.1328 4.56562C13.1816 5.07492 14.0656 5.8696 14.6833 6.85847C15.301 7.84733 15.6274 8.99032 15.625 10.1562C13.9086 10.1562 12.5 11.5648 12.5 13.2812C12.5 13.9805 12.7422 14.6141 13.1352 15.1367C12.0509 15.9531 10.7323 16.3983 9.375 16.4062C8.0177 16.3985 6.69907 15.9533 5.61484 15.1367C6.02371 14.6043 6.24682 13.9525 6.25 13.2812C6.25 11.5648 4.84141 10.1562 3.125 10.1562C3.125 7.71875 4.52344 5.58125 6.61719 4.56562L6.61719 4.56562ZM3.125 11.7188C3.99688 11.7188 4.6875 12.4094 4.6875 13.2812C4.6875 14.1531 3.99688 14.8438 3.125 14.8438C2.25312 14.8438 1.5625 14.1531 1.5625 13.2812C1.5625 12.4094 2.25312 11.7188 3.125 11.7188ZM15.625 11.7188C16.4969 11.7188 17.1875 12.4094 17.1875 13.2812C17.1875 14.1531 16.4969 14.8438 15.625 14.8438C14.7531 14.8438 14.0625 14.1531 14.0625 13.2812C14.0625 12.4094 14.7531 11.7188 15.625 11.7188Z')
                                                                    ..color = Color
                                                                        .fromARGB(
                                                                            255,
                                                                            0,
                                                                            0,
                                                                            0),
                                                                ]),
                                                          ))
                                                ]);
                                              }),
                                            )
                                          ]),
                                    ),
                                  ),
                                ))
                          ]);
                        }),
                      )
                    ]),
              ))),
    );
  }
}
